module.exports = {
  status: 200,
  headers: {
    'content-type': 'application/json; charset=UTF-8',
    date: 'Fri, 18 Aug 2017 13:58:16 GMT',
    expires: 'Sat, 19 Aug 2017 13:58:16 GMT',
    server: 'mafe',
    'x-xss-protection': '1; mode=block',
    'x-frame-options': 'SAMEORIGIN',
    'cache-control': 'public, max-age=86400',
    age: '66992',
    'alt-svc': 'quic=":443"; ma=2592000; v="39,38,37,35"',
    'accept-ranges': 'none',
    vary: 'Accept-Encoding',
    connection: 'close'
  },
  json: {
    geocoded_waypoints: [{
      geocoder_status: 'OK',
      place_id: 'ChIJebmqOYlw44kRh66YLunn_-0',
      types: ['postal_code']
    },
      {
        geocoder_status: 'OK',
        place_id: 'ChIJy7cGfBlawokR5l2e93hsoEA',
        types: ['establishment', 'point_of_interest']
      }],
    routes: [
      { bounds:
        { northeast: { lat: 42.3674676, lng: -71.0517026 },
          southwest: { lat: 40.70171879999999, lng: -74.0161653 } },
        copyrights: 'Map data ©2017 Google',
        legs:
          [ { distance: { text: '216 mi', value: 348111 },
            duration: { text: '3 hours 39 mins', value: 13156 },
            end_address: '285 Fulton St, New York, NY 10007, USA',
            end_location: { lat: 40.7129366, lng: -74.0139476 },
            start_address: 'Boston, MA 02113, USA',
            start_location: { lat: 42.36553, lng: -71.05528389999999 },
            steps:
              [ { distance: { text: '0.1 mi', value: 187 },
                duration: { text: '1 min', value: 67 },
                end_location: { lat: 42.3670453, lng: -71.0542919 },
                html_instructions: 'Head <b>northeast</b> on <b>Salem St</b> toward <b>N Bennet St</b>',
                polyline: { points: 'qoqaGn~tpLg@YOIIESKg@Wi@]ECIEs@a@k@]WO' },
                start_location: { lat: 42.36553, lng: -71.05528389999999 },
                travel_mode: 'DRIVING' },
                { distance: { text: '0.1 mi', value: 234 },
                  duration: { text: '1 min', value: 79 },
                  end_location: { lat: 42.36822, lng: -71.05664689999999 },
                  html_instructions: 'Turn <b>left</b> onto <b>Charter St</b>',
                  maneuver: 'turn-left',
                  polyline: { points: 'ayqaGhxtpLQj@Ob@KVWt@MZKXELe@dAAB{@pB_@x@' },
                  start_location: { lat: 42.3670453, lng: -71.0542919 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.1 mi', value: 171 },
                  duration: { text: '1 min', value: 61 },
                  end_location: { lat: 42.3672093, lng: -71.0582036 },
                  html_instructions: 'Turn <b>left</b> onto <b>Commercial Street</b>',
                  maneuver: 'turn-left',
                  polyline: { points: 'k`raG`gupLFLDJ`A`BDJFJNTLTPVRXBP@B@B@BJLJNDF' },
                  start_location: { lat: 42.36822, lng: -71.05664689999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.2 mi', value: 285 },
                  duration: { text: '2 mins', value: 101 },
                  end_location: { lat: 42.3647904, lng: -71.05838349999999 },
                  html_instructions: 'Turn <b>left</b> onto <b>N Washington St</b>',
                  maneuver: 'turn-left',
                  polyline: { points: 'azqaGvpupLZf@JPTVRKXKtBIpBI\\A^@H?fAA' },
                  start_location: { lat: 42.3672093, lng: -71.0582036 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '348 ft', value: 106 },
                  duration: { text: '1 min', value: 37 },
                  end_location: { lat: 42.36384839999999, lng: -71.058433 },
                  html_instructions: '<b>N Washington St</b> turns slightly <b>right</b> and becomes <b>New Chardon St</b>',
                  polyline: { points: '}jqaGzqupLFH@@@?L?p@@T@V?d@AZC' },
                  start_location: { lat: 42.3647904, lng: -71.05838349999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '315 ft', value: 96 },
                  duration: { text: '1 min', value: 17 },
                  end_location: { lat: 42.3632053, lng: -71.0577247 },
                  html_instructions: 'Turn <b>left</b> onto the <b>MA-1A N</b>/<b>Interstate 93 S</b> ramp to <b>Quincy</b>/<b>Logan Airport</b>',
                  polyline: { points: 'aeqaGdrupL^GBMBI@GFINOd@k@V_@' },
                  start_location: { lat: 42.36384839999999, lng: -71.058433 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.4 mi', value: 632 },
                  duration: { text: '1 min', value: 37 },
                  end_location: { lat: 42.3593851, lng: -71.0523058 },
                  html_instructions: 'Keep <b>right</b>, follow signs for <b>Interstate 93 S</b>/<b>Quincy</b> and merge onto <b>I-93 S</b>',
                  maneuver: 'keep-right',
                  polyline: { points: 'aaqaGvmupLTK@ABCHILOLMR[T]l@aAn@qA\\w@Ti@FO`@cAFQDON_@@A@EJWXs@Xq@@E?CDa@N]p@uAr@sAb@s@T[`@a@h@_@FEFCFCNGZIh@M' },
                  start_location: { lat: 42.3632053, lng: -71.0577247 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.2 mi', value: 388 },
                  duration: { text: '1 min', value: 19 },
                  end_location: { lat: 42.3559811, lng: -71.0514754 },
                  html_instructions: 'Keep <b>left</b> to stay on <b>I-93 S</b>',
                  maneuver: 'keep-left',
                  polyline: { points: 'eipaG|ktpLNEz@Q|@U~@QvA[fBi@`B_@JATERCRCVAN?L@N@NBNBLD' },
                  start_location: { lat: 42.3593851, lng: -71.0523058 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.8 mi', value: 1253 },
                  duration: { text: '1 min', value: 59 },
                  end_location: { lat: 42.347975, lng: -71.0608457 },
                  html_instructions: 'Take exit <b>20A-20B</b> for <b>Interstate 90 W</b>',
                  maneuver: 'ramp-right',
                  polyline: { points: '{soaGvftpLRHRJVJRHRLVPRRVZV^PVNVNZP\\Pb@p@zAt@nAfDpHPb@H^Lb@Hh@Hn@L|@Hj@Lv@H^BTBPDb@V|@Vp@Tf@P^Zd@p@r@XXf@RXPb@Nf@Pd@Jh@N^J^Fd@Fd@DZFhCl@PJJFNJNJx@h@j@^JFJFLJ' },
                  start_location: { lat: 42.3559811, lng: -71.0514754 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '3.2 mi', value: 5080 },
                  duration: { text: '4 mins', value: 236 },
                  end_location: { lat: 42.35531210000001, lng: -71.1185029 },
                  html_instructions: 'Keep <b>right</b>, follow signs for <b>Route 90 W</b>/<b>Mass Pike</b>/<b>Worcester</b> and merge onto <b>I-90 W</b><div style="font-size:0.9em">Partial toll road</div>',
                  maneuver: 'keep-right',
                  polyline: { points: '{anaGhavpLNHNJLHFDl@`@FDLJFFJHFHLNFHFLDJDLDVBH@HBF@D?B@H@HBJ@J?H@H?H?J?H?JAJ?LAPANARCVCPCVEv@EZEXG^EZEVGXE\\GXYpBGZEZEXE\\E\\CTC\\E^AZC\\C\\[fEC\\C`@AZCXA\\CXAZA`@AX?\\?ZA\\?nO@pB?xDL`R@xBF~JDbG@hA@hADhLDfLDrE@xC?ZAVC`AAZA^Er@Gz@IbAGdAAd@A\\Ad@?p@?r@?tA?rB@bE?|@?tF@lC?rD?tC?rCBfI?rA?z@Az@?f@C`@Af@EbAEr@E`@CZSnBq@|F_BrNa@tDWzBKr@WpAOv@c@hBa@nAUr@Uj@KX[p@Sb@m@pA}@nBo@rAEJKTKVKXKVELGNGTIVK\\K\\GVK^ITIZK\\IVIXKVKXMVKXMVKXuErKe@fAMXMVMROVMR]d@QPc@b@]VYRk@ZWJ{@d@' },
                  start_location: { lat: 42.347975, lng: -71.0608457 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '52.1 mi', value: 83793 },
                  duration: { text: '48 mins', value: 2855 },
                  end_location: { lat: 42.1324802, lng: -72.05108369999999 },
                  html_instructions: 'Keep <b>left</b> to stay on <b>I-90 W</b><div style="font-size:0.9em">Partial toll road</div>',
                  maneuver: 'keep-left',
                  polyline: { points: 'uooaGriaqL_Ab@iAl@_@VMHOLa@`@MLk@t@]h@KPUf@Sj@K^ELQt@ETCPGf@]`FANEd@ANCr@A`A?Z?|@?fABj@@^HzAHp@D\\BTLj@Hf@`@jBDPRt@Pt@ZrALv@FZFZD\\DXHz@D^Dp@Bj@BV@d@@l@@H?x@?t@An@Ab@A^AZCb@AXGx@Gv@ARMhBSpC]`Fk@bICf@OtB]`F?BCXOtBSzCInAK~AKlBKvAKxAQxCGz@Er@OrBUrDGt@E~@G|@AVAd@C|@An@Aj@?r@@x@?n@DvABn@FtAJvARtCLtBHpBBz@D|@?`@DvBBvB@z@@z@?x@@^@dA@dAFnFFvDBdD?v@?@@t@VvT?D?t@?@?DB~@HjIJ~J?H?fG?^?l@CbEAfAGfDCnBGvBEpCGzEGfFIlFKrG?z@?n@D~DFzAHxAH|@Hx@`@jD^jC?Bh@vDZbCZ`CBTF^?BLv@VzBX|BLbALfAd@zENzAFt@HfAFf@^fDLh@J~@\\lCp@dFf@zD^nCR|ALbAFZDZN~@Nx@RjAHf@\\`Bf@jCHd@d@zBZ`Bj@vCr@vDlAhGTjA`@rBH^DVLp@P~@Jh@Nx@ZpBZlBTdBRtAPxARzA\\zCB\\JfAVlCJpAZzDXnEBVb@hGVlDVxDHpATrCRzBPdBHn@R`BVjBn@pExAfK`@tCVfBh@nFBTPjCHfADbAF~@B|@@NFlAXdHFrANpDFlA@h@Bh@Dt@NtD@TDj@NlC?DFhADf@B\\H`ANpBJvAHx@Fx@Hz@Dz@Bv@B^Bt@@v@@t@@jA@|A?t@BhBBjAB~@DbA^bJHzBNpD?BDp@rAl[Br@JpBLtCDbAFp@Fn@Hz@Jv@Jj@RfAJl@Pn@Rr@Tn@Rl@Zv@Th@NXR^l@hA|@|Af@x@d@x@T`@Zj@Vl@NXN^Rh@HTJZBHL`@Lb@Rz@Hd@H^DTJp@\\nBlApHVzANr@T~@ZbATt@Xt@P`@JVHPHRNXR^Xb@xBtDv@xAh@jAJTHTPl@Jd@Pr@F^Lt@Nv@Jx@L|@P|AP|AD`AB~A?b@?b@?bACzBAp@GfFC`BG~JAv@Av@ClBAjA@z@?x@@|@@x@DtABz@DvADxADx@@b@CXh@pQVxILtDFvBFrAFvAFz@HvAHx@JtALtAPxAHv@PvABV`A|HZhCD\\n@bFt@pG~@nHd@vD^zC\\pCZbCXvCHv@PtBH`AJ`BJbBJpCFxBFjD@tC?`BAjBC|LAl@A|A?@?DAnC?HAz@?z@?\\?nB?L?x@BzA@t@DfBDlAD|@JdBLlBLdBLrABLNtALlAHj@PnAXhBZfBh@jCt@bDDRPl@^xAh@bB~@jCRj@fAbDNb@rDxKzClJrDvKjAhDlB|Ff@zAx@~B~@nCdA`Dv@vBnA|Cv@fBdAvBh@bAv@tAx@tAh@z@b@n@b@l@V`@`@h@f@p@`@l@Zb@nAfBh@t@`ApAt@bA~BbDvAnB`B~B|AxBlApBh@~@dApBZp@j@jAXp@\\x@l@bBN^h@~At@`CFVFTNj@l@dCVhARbALt@P`APbALz@f@bE^`En@bJ\\vEHpAPnBFh@LlAXxBZlBDRVtAXtAPt@\\pAZdANf@FTVr@b@nAZz@j@tA^v@b@|@f@bA^t@NVvApCjBlDd@dAf@hA\\z@`@jAXv@h@dBFVf@hBb@pBZ|ATtAXlBRbBZ|CN|BB\\F|AFpB?XBzA?jC?pAE~BGtAGlAI|AAROhBeA`Mi@jGe@tFOpBQrBW`DWvCy@vJOdBAPCRmA|NG~@E`@C^C\\C\\u@lISjCCXwAnPo@`Ik@pGUxBoBhQK~@MhAAJI|@QzA]vDQnBMnBOlDEdBCpBAtA?dC@~ABjBFbBFbBFpANdCL`B`@~DTdBXhB\\zBd@vCl@~DZpBF^@BHd@b@pCHf@Hh@PjAxBdNXnBtA|Ir@rEdA`Hb@`CfCnPf@zC|@~Fx@dFHj@j@hD~AhKnA~HZpBHh@@BHd@^|BH\\d@xBb@dBV`Ad@vAx@~BP`@Tl@n@xA\\t@j@dAl@lAt@xA`ArB@?nAdCfC~EtDrHNVvA`D@@p@`B`@hA^hA^hAl@vBn@dCVhAVhATfALz@BLb@lCLbALbANjAJjATbCJvAFfADbAHfClAxf@L`FJrDDpBLdFJnELtEDbAHfBF~@F|@Df@Fn@DXRhBNbA^|B\\nB^fBV`AZlATt@X~@\\~@x@xBBH\\v@Xp@Zp@pA|BzAbCrAfC~@~AXb@Xd@l@fARZtK|Q^n@RZBDDHHN^n@h@z@j@bAj@`Al@bAv@rAj@`AXd@Xb@f@z@f@|@p@hAt@nAl@dAh@|@j@`AvAbCzAhCv@pAx@tAl@bAj@bAh@|@h@bAp@hAb@|@h@hAd@bAZt@j@rAd@nA^`A~@pCf@`BBH`@zA`@zAh@zBh@hCTnAVvA`Pj{@~AvIbDdQpAzHJl@@B@JF\\RjA|BzNv@hF`Hvb@PjA?@N~@V`BPfAV|AXfB^~BrCnQRhAlBxLhAzGRvAVxA?@N~@hAdHdAzGTtARrAp@bEZpBj@lDj@jDJt@PbATvAbBjKPlAPfA\\pB^fC`@dCLr@^vBZpBj@nDhApHP`ADZ@Db@pCd@lCb@`CZzAZvAPp@FTn@zBFT^fA~@zC`BfFz@jCRl@^dAx@bCzBvGDJFRf@|Ah@~A@Bf@xA@BbGxQz@fCp@rBj@fBPd@?@DL?@@@|@pClBzFz@`C\\~@Xp@v@bBv@bBl@hA`AbBPX\\h@h@v@z@lAb@j@RXTVhArAf@h@v@v@~@|@vBpBbCzBnAhArAlAjAdATRPLpBhBv@r@bA~@~BrB`@`@dExDfB~AxApAhB`BbCxBlAhAhAbAhAbAh@d@vBlBzBpBnCdClCbCZX`BzAxHbHl@j@bAdAl@n@dAlAj@n@nA~AtAfBfA|AV^zA|BjB~CpErHzDpG`DnF`A`B|AjCfAhBnA`CPXh@dAfBxDnAzCn@~Ap@bBnFdNnBbF`@dA|@~BVl@^|@x@xB`@bAz@vBlAxCfArC|@|Bb@hAtBnFt@nBZ`Ad@xA`@xAr@`CNt@R|@Nn@Jl@Ll@t@jEjArHRrAL~@vCxQnA~HRvAJt@Jp@NvAJbALnAFx@JlANnCHjBDjBDlB?v@@t@?j@AhCAp@CrAAb@Cn@GlBGdACd@QjD[dGK|AOrCg@pJUpEUlEo@vLKlBOzCMvBUfEOvCw@bOQvCAd@QpCGxAEn@IrCEvB?dAAlB@vA@dBBhABx@DrABb@FvAHrAJvADh@LjAJ`ABZHp@PvAvBdPR`BVpBPrAHt@Jx@PnBNlBHpA@N@ZBj@Bh@Dx@@z@@h@B|A@bA@V?T?f@AxACjEYtTMpKMpLM~KIhFKxIShPEvEa@f^AfCBnDDvBNtD?@H~APtBF`AJ~@RlBPzARrAj@hD~@|Ed@fC~@xE^pBNt@bCnMBLf@rCh@nCH`@`@bC`@jCp@~En@fGXjDJxAXfFRnF@d@DnA@f@@t@@VFfJVpZRvVPdQD|E@`BDfEHdJBnDBxA@vADvFRlT?P?L@xBHtG?x@D`E@j@?h@DtCJhFBv@@d@FpBJrCLnC@LJlBFfAJrBRrCVjDb@dFPdBZ~Cd@fEPrAd@jDf@hDbAlGRnA\\dBBPVrA`A|EhAfFPt@XjA\\vAlBfHJ^`@tAf@fBb@rAh@bBh@~Ab@nAVv@t@tB|@`ChApCfAnC~@vBnAtC|@vB`A~Bn@vA~@zB`AxBhApCp@xAXp@jCjGrA|CjBlEhAjCdAfCVj@N`@@BLV?@?@JV@??BR`@?@FLbDvHRf@JT@@HR^z@Vn@Vt@Rh@n@nBh@bBZlAZlALn@f@~BDPBLf@xCL`Ad@lDb@vDFt@Fr@@NDl@FfAFdADxAFnCDbCLfHH`FFxCDtCFlDJ~FDjCHfEFtBLxDJvBLjCLvBPhCTtCLzANlBJ|@\\nDb@zDVtBjBnONpAL~@h@jEHx@f@dERfBP|A^~DRfCb@lGh@xIH~ATzDFnA@?Dx@`@tGZtFNbCNtCf@rIN~BNzBJxBJzADj@NlBTjBJx@LbAPhAJf@Nz@Nv@^bBZlARv@^lA^jAb@nAd@jAb@dAVl@\\p@v@zAh@bAj@`AvAfCbCjEb@v@f@`ALTn@tAr@zAp@dBP^BH^bAnA|CJXBJFPVn@HVlAhDJXp@lBTn@`@pAZ~@~A`FpAjE`AhDp@hCThAXlAVvA^jBZvBPtAZrCTtBLlBLrBHdBHvBBhADtALpEF~BVvIHpADv@JvAJzAFn@LrAJ|@TfBPtAVvARjANz@R`A\\zAH`@ZpA\\lAh@fBh@fBj@bBl@dBj@`B~@pC@Bt@dCp@pBj@dBRp@L^b@|Al@hCTdATnAjFdZhBbKz@zE`AlF|@bF\\rBLr@PtA\\tB`@dDf@hDnApJ|@tG~CnUBJ@LNjA`@`CN|@?Bp@~DFZ`AtElAtFrChKpHnW?@nAnETz@XdAb@lBZrAZnAH`@v@vDv@hE|@pF`@zCL|@PrAx@vGt@dGp@zFl@pENjAR`B^bCn@zDp@pDf@dCRz@Pz@R|@Nl@\\vA~@nDJ^Tz@Vz@HZZbA^nAn@nBTp@^fAJXVr@h@vATn@Xn@d@nAd@fA`BxDtAdDjAnCdB~D|BrFz@rBz@nBHRt@fBhBhEl@tAhAlCBFx@nBn@xAn@|Ap@|Aj@tAbAjCp@fBn@dBt@~B\\bAjAzDfAvDlAbEdAnDTv@`BrFh@jBzA`FnEjO?@nAdETv@Tp@Vt@~ArEh@tAp@bBjAvCrA|Cz@hB^|@nArC|AnDbAbCTj@`@jAd@vA\\bALb@`@vAj@vBNl@XlA`@lB^vBd@pC`@lCNhA\\zCJhAHz@JpARfDJ~BF`BXrPHxFPlLNjKL~FDnARfEBr@LfCLzBBPHhAHr@B\\^dELxATlBP`BTjB\\nC\\jCJz@PrAX`CPvA`@`D^bDDXb@jDL|@XfCZbCj@pENhAj@|Ed@tD\\lCl@|ExAxLz@zGVrBd@tDVhBh@hDLz@l@bDNx@n@dD^hBRx@t@|Cx@dDRr@Rp@r@hCj@hBx@fCtAzD\\|@vArDnB`FxDrJt@lBz@vBdAlCrBjFn@~AhAxCh@zAl@hBt@|Bh@dBTv@~A`GXjAr@vCt@jDLp@Nr@d@dCl@bDf@lCXtAZbBt@|Dl@xCx@jEj@fClCtLp@tCdDzN`GxWpAvFtAvGfAxE' },
                  start_location: { lat: 42.35531210000001, lng: -71.1185029 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.9 mi', value: 1489 },
                  duration: { text: '1 min', value: 64 },
                  end_location: { lat: 42.1267354, lng: -72.06602769999999 },
                  html_instructions: 'Take exit <b>9</b> for <b>I-84</b> toward <b>US-20</b>/<b>Hartford</b>/<b>New York City</b><div style="font-size:0.9em">Toll road</div>',
                  maneuver: 'ramp-right',
                  polyline: { points: '__d`GfnwvLRrAzB|JH\\H`@H\\FXF^FXD\\F\\BZD^BVB^@\\B\\@Z?^?TA^?^A`@AZCZAZQnCC\\CZC\\AZA`@AX?\\?X?\\?ZB`@@^BVBZB^D\\DVF\\F\\FZHXHXHZJXJZHRLVLVLTNTJRLPLPRZNRPPLNNPfH`I`AjAfCrCfCnCVZ' },
                  start_location: { lat: 42.1324802, lng: -72.05108369999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '40.9 mi', value: 65777 },
                  duration: { text: '35 mins', value: 2114 },
                  end_location: { lat: 41.7644068, lng: -72.6313758 },
                  html_instructions: 'Continue onto <b>I-84</b><div style="font-size:0.9em">Partial toll road</div><div style="font-size:0.9em">Entering Connecticut</div>',
                  polyline: { points: 'c{b`GtkzvLJJZ`@n@r@nE|EzAfB`IdJl@r@~A`Bn@n@^\\l@h@jA|@pA|@xBrAhCvAnAp@nBhAfAp@PJ^X\\X`@\\l@p@`@^Z^TTPVl@z@PTT`@JNNTXj@f@~@|@hB`CxEp@tAj@jAl@fAd@v@PTNVn@|@JLBFBBDFFHPTDBl@n@l@j@pAfAfAv@v@f@|Az@n@Xn@VpC~@`AVb@LLDf@P@?XH~@V\\LzIdCpGjBdDx@dCf@nHtAnCf@p@LnCf@rB`@h@JlB\\`ARTDVFVF^Hb@J^Jd@Lz@VpA^JDlBp@nBt@VJTJTJ^NZNf@Tf@Tf@Xh@Vv@b@|@f@lAt@f@ZXP\\TlA|@jA|@t@l@~ApA~BlB`ClB|BjBjDpCt@l@|CfCpCxBr@l@l@f@rAdA|@r@vAdAlAx@^ThAr@hAp@lAn@r@`@`Ab@pAn@rAh@|@\\rAf@|@ZhBn@pAd@~CfAJDNDz@Zr@ZfAb@j@VXNxAr@dAj@t@\\x@f@nDbCx@j@zAjAdAz@lAbAhAbAdA|@f@b@t@p@b@`@t@t@t@p@d@b@r@p@p@l@jAdAlBfBnBbBLLRNz@r@LJ~AjA`BhAdFlDx@h@x@l@f@\\b@Xt@d@j@`@B@?@l@`@XNd@Zf@\\t@j@PLz@n@x@j@fC`Bd@\\~BzAb@VVP^TVNd@X\\RxAz@nAx@d@X~ExCRJ|ClBx@h@XNh@\\h@ZZRVN^THFDBTNTNlAt@jAt@h@\\jAz@jAx@fAt@fAv@xAhAfBtAfCrBhA~@zAnAb@^v@p@x@l@d@\\v@l@f@\\pBtAd@Xh@\\tBlAz@f@`Bz@h@V`Af@dAd@rAj@lBv@jFnBx@Z`Br@pAn@vAt@p@\\`@TTLNHLHNHLJXPnAv@vAbATPz@l@fA|@dAz@xAnAXTfA|@~BpBnB`BzAnAv@p@~BpBhA~@hA`AlCzBnAdAd@^t@p@hA~@v@p@bAx@|AtAt@l@l@d@t@p@jA`AXTZXd@^LJf@b@b@\\RPTR^ZJHHHLJl@h@f@`@j@f@RNb@^rBdB~BpBfDpC`@ZrAhAl@h@f@b@NN\\^^d@TXX`@V^Vb@R\\h@dAXn@r@tAb@~@h@dAv@zAv@|An@hAHR\\l@^p@dErH~IdOzAbCdAhBjBzCl@bA^l@l@`ALT^n@jBxCP\\l@bAn@bAV\\NTT^PRPTp@x@b@d@^`@d@b@f@b@x@n@f@\\ZR\\Tz@j@|@j@x@h@|@j@bBfA|BxAlCdBnAx@z@j@lAt@~@n@fBhA~@l@bBfAzClBhBfAlC~A`Af@~@h@bB|@~BrArCzAnAr@h@Xl@Z~@f@rAp@hB|@tCrAtAn@`Af@~@b@tAp@lB|@~@b@tAp@rAn@lB~@`ChAtAr@tAr@z@f@rAt@dBfA|@j@pAz@|@n@`BjAx@l@zDtCdBnARNbBnAnA`ApA~@`@ZfBrA`Ap@`Ar@VRVR^V^V\\X^V`@X|@l@b@\\b@\\`@Z`@Z`@Z^Xd@ZnA|@\\VVRRNVPh@`@n@b@ZVv@j@^Xp@f@n@d@n@d@`@V`@VPLv@h@v@h@z@h@x@f@f@\\z@h@p@b@r@`@h@Xj@^d@X`Aj@p@^r@\\TNd@Vd@Vh@Xj@XZPTNVLZPZP|@b@z@d@bAf@`Ah@ZP\\PRJRJ`@Rh@Xh@Xf@XRHx@b@t@`@t@b@~@h@x@f@n@`@j@^r@f@PLd@ZjAz@jAx@h@`@h@^t@h@lAz@VPd@\\f@^RJz@n@RLb@Zd@Zp@d@p@d@dAv@l@`@r@f@pA|@dAt@p@f@r@f@r@f@r@h@~@n@ZT\\TZRv@j@b@\\b@Zf@\\f@\\RNd@Zd@\\xAbAdAr@dAt@XRXRXTZVRNx@h@v@j@b@Z`@XHFPLPLn@b@n@b@RP`@Xb@VPNRNRNlAx@f@\\f@^NJb@Zb@Zp@d@p@d@r@f@d@\\\\VTPh@^l@`@ZTVRf@\\f@\\lAz@XThAv@|@n@|AfA|AhApDdCvAbAxAbAf@^f@^v@j@f@ZPN\\TXR\\V\\VrA|@fAv@PNzAjAfA`ALLXVXVfAhA^`@b@d@x@~@Z`@JN`@b@NRRXRZRTPVNV\\h@^h@PZT`@Vb@V`@N\\^n@P\\PZP`@Xl@Vh@Vj@Tj@HPb@fATl@Nb@N`@L^Pd@Pd@\\jA\\jAX|@X~@v@hC`AnDn@|BbApDjBtGj@xBjAfEt@jCt@lC`AfDvB|Hh@lBj@lBv@lCr@pCtBnHbApDz@|Cl@|Bl@tBf@pBjAfEd@~A`@nAZ`A`AxCjBjFzAfErJpW`@bA`r@hkBxCnIxBxEfCtErAnBlAxA|C`DlB`Bp@h@pC~BhDhCl[zV|`@r[rArApB`BvDvCzC`C~ApArC~BtB|Bt@~@VZ`AvAjArBhAzB^z@j@zAl@hBL`@HRPn@@BPp@`@jBd@dC@HNx@b@zB^lBl@|CPx@\\`BV|@Pp@Ph@Rp@Xx@Tl@Vl@Vj@j@fAv@tA`@p@j@z@fAvAfAnA|@~@dDbDt@r@`A~@vAtA`C~BhBpBDDDDjBzBl@x@|@zAjAzB\\r@\\v@L^`@fAFLjAhD~BrG~@nC|@|B~C|IvBhGZ~@Pj@fBdFJZbBvEnC|HtG~Qd@pAz@`CN^N\\Pf@jF`Ov@xBN`@~AtErAvDjDzJdG|PbC|GfDlJn@fB`BxErElMhBhFrBzFpArDnAxDb@nAv@zBb@nAZ~@Vt@n@bB`@lAl@dBv@vBb@jAt@vBt@vBl@hBVr@Vp@|@dCf@tAb@nA\\bAfB`FzBnGv@zBv@xB~@nCjAhD\\~@b@hAd@rAl@bB`@nAb@hARl@^bAv@zBb@hAx@~Bv@|BfA|Cp@jBp@lBh@zAbAhCh@zApArDbArCBFHTTp@t@nBxAdEp@pBxHlTrFxOf@tAf@xAfA|Cf@tAj@~Al@`BJZTl@`@nAj@zAp@bBVj@HPN\\LXDJ\\t@n@nAlAzBjBlDfArBdAlBl@jAb@|@l@tAVr@N`@Tp@Rn@\\nAXnATfAPz@TrAd@zCZtBXlBf@dDXnBRrA^fCXpBZvBTbBp@rEt@fFl@dEr@`FPjAJx@P`BJbADt@Bl@BhABt@?n@?b@AdACv@Cz@Er@IfAGr@Gl@E\\Kp@QdAUhASz@e@dBu@hCiBnGSp@Sp@Md@Sz@I`@Kj@G`@O`AE`@E^Ef@Gp@El@Ej@Cv@At@C`B@bB@r@Bf@Bh@Dx@Fx@Dj@Jv@Hn@Jp@Jl@Jj@Pr@Pr@d@lBr@tCPv@Jj@BHLr@L|@Jt@NxAFx@B\\Dv@@j@B`A@pABhD@|B@pBDhGBnDBbF@rB@|B@pD?b@At@Ax@Cl@A^Ef@YbFgB`ZGhAG~@GlACbACh@Ar@AjA?lA@`A@nADlABh@Bh@HvAFbAJ~@Hv@RzAHh@Lv@BLHh@Lj@Jb@TbA`@~Ab@vARl@Xx@Xr@`@`ANZx@`Bb@t@Zh@l@|@\\f@`@l@lFhH`LnO~J`NnKrNRX^j@\\f@x@rAn@fAdApBn@pA\\v@j@nAp@|AjNj\\rA|CXl@bFpLbBzDxBnFpCtGzChHbB`E^|@rA`DdGnNfAlCpAzCf@lAfA~B?@Pb@Tj@Zr@Th@Rf@b@lA`@fA`@lAd@~Ad@bBXjAXjAZpARbARdAR`ALv@Hh@\\rBRpAr@pEHh@@HF^x@~E|@|FbAvGv@bFpAlItAtIz@lFrApIj@fDrAnIXhBtBtMzAxJHd@BPxBdNlAvHd@zCJn@\\rBTvAXjBRrARnANz@XrAPt@H\\Rv@ZhANf@Nb@J\\Xt@P`@FPNZR`@jCtE~@zAdAxAnBnCnP~Ux@jAf@r@vArBb@n@j@v@\\h@x@lAp@fAl@bAj@dA^r@d@|@f@dAZr@f@jAZv@d@hAf@tAn@nBRr@`@rA`@zA\\pAVfAPz@pAdHPjA@FVfAJd@R~@Nr@h@vCNn@XtA^~A^tAb@~ANj@^hA\\dAv@xBf@vAh@lBl@dBt@|B~@hCFPr@nB|@jC~ArEbDhJX|@Rn@BHn@zB`CpJbA`Fn@~Cf@pCd@tC|@bGd@`EZtCVnCJtALtATfC\\bDFn@Jv@Dh@nAhNVlCFj@Fh@Hj@Jp@Fb@Ln@H`@Jd@FVBHFXDN\\jAH\\N`@f@rAPb@Rb@f@dA^p@b@t@Zh@d@p@fApA|@~@ZXn@h@VP^ZxAfAbAr@nGtE`D`CjAz@FDdBpAxDpCtF`EVRxAjAhEnCjTfNt@d@jAx@bAf@|Az@HFxJhGvBnAdAr@xA~@nAv@n@^j@\\rAz@XPtCfBx@h@|@h@hAp@p@b@n@`@p@b@v@d@l@^TP\\Tp@f@x@p@r@n@TTXVn@p@TV^b@f@n@RVV^v@jA^j@`@r@Xd@R`@`@t@Tf@Xn@|@|BN\\Vv@Ph@Ld@Rt@V|@Tz@?@HZJZJ`@Ld@XlATjAJp@BJ?@N`ABLF\\Ff@Fd@Fb@Ht@Dl@B`@Db@Bj@Bn@Bn@Bb@DzA?hA?~@AhCAhCAvB?v@ArB@x@@z@@x@BdABz@Dv@Dt@Fz@XzDHpALdBZrDPfC@FLdBPrBh@dIlAvPb@~FRfC`@`FPrCLzABT?@t@dK\\|DZ|CPvA\\jCfAfH~@~FxAjJv@zEn@~Dx@vDbDxRF^ZnBd@vC~CvQzBbMdAzFvBpNxC~Q' },
                  start_location: { lat: 42.1267354, lng: -72.06602769999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.6 mi', value: 911 },
                  duration: { text: '1 min', value: 33 },
                  end_location: { lat: 41.7597762, lng: -72.64016509999999 },
                  html_instructions: 'Take exit <b>57</b> on the <b>left</b> for <b>CT-15 S</b> toward <b>I-91 S</b>/<b>Charter Oak Bridge</b>/<b>N.Y.City</b>',
                  maneuver: 'ramp-left',
                  polyline: { points: 'qb|}FbyhzLPVBDBHLp@HZLv@VpAl@bDXlARr@Xr@@Bd@dA?@BFN\\NX^l@JPNT^f@NVPPNNPRh@h@l@j@`@`@LNPPLN@BLNX^JNb@r@LTJPLVJRJTXj@JXRj@HTJZRn@Nn@HXDT\\jB' },
                  start_location: { lat: 41.7644068, lng: -72.6313758 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.5 mi', value: 813 },
                  duration: { text: '1 min', value: 29 },
                  end_location: { lat: 41.7566592, lng: -72.64896639999999 },
                  html_instructions: 'Continue onto <b>CT-15 S</b>',
                  polyline: { points: 'se{}F`pjzLTnAFXTjATlANr@Lt@Nr@VpA\\hBBLFVNz@BL@FFZ?@Ll@|@xEVjANp@XjATp@^pAh@|Aj@vAP`@JVJTVj@JTLT`@v@' },
                  start_location: { lat: 41.7597762, lng: -72.64016509999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.8 mi', value: 1346 },
                  duration: { text: '1 min', value: 51 },
                  end_location: { lat: 41.7479184, lng: -72.659972 },
                  html_instructions: 'Continue onto <b>CT-15 S</b>/<b>US-5 S</b>',
                  polyline: { points: 'crz}F`glzLv@zAT^FLLRZj@LTLTLRNTFJDFLTj@~@n@hAp@hALPLVNVh@~@LTZd@LTLRPXNVNTZf@NXh@|@fAjBvA~Bz@vALTPVZf@NVLTNTLRNTNTLRPXNTNTHLNT@B`@h@NR\\d@PR`@f@JLDDNPPPPPNPTR`BlAbBnAb@X\\RbClA' },
                  start_location: { lat: 41.7566592, lng: -72.64896639999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '17.1 mi', value: 27505 },
                  duration: { text: '15 mins', value: 919 },
                  end_location: { lat: 41.5340816, lng: -72.7674986 },
                  html_instructions: 'Take exit <b>86</b> to merge onto <b>I-91 S</b> toward <b>New Haven</b>/<b>New York City</b>',
                  maneuver: 'ramp-right',
                  polyline: { points: 'o{x}FxknzLHNBDDB\\Nt@^x@`@jAh@pAl@lAj@tAl@vCrAjAh@jAh@~@^^N`@NXJZJhA^@@VXn@Rf@Nz@T`B`@pA\\bAX`AVnFtAjAVjAVh@JZD`@DXD^DVDXBT@T@T@f@@`@?Z?\\?l@Ab@ATA\\Cd@Gj@If@Gr@MVGZI^K`@Mz@Yd@S^O^Qn@]|@g@x@i@d@_@b@]x@u@d@g@j@q@x@aAh@u@V_@`@o@|@yAZk@^s@b@s@R]j@cA~BcExCoFp@kAh@{@fAgB\\i@b@m@dA{AzB_Db@m@b@k@dBqB^e@`@i@RUb@m@PURUd@g@PORQRORORMROROTOVM~@i@TKTKl@UTIVIj@MVETEXEn@In@Il@Kn@Kp@KrAS`AQ`AQh@IfAQp@M`AQdAU\\Gh@K|@U|@WFCTGTIj@Sz@[f@STKRGRKRIxBaAnAi@h@WHCHEXKdCkARKVK`Bs@RIpAk@f@Sj@Yd@Sj@Uf@Sf@U@?tAi@rAc@j@Or@Wf@MTIRGp@Sj@QFCv@SVETERCRCn@Ih@IXETEpC[RCHArAOl@I`@Gd@E`@It@Oh@K\\Gf@G`AOVEj@Gj@Il@Il@IRCTERCTCl@ITCRCTCTCTCTCh@C`AEd@AZ?j@?`A?~@?h@@V@h@D|@FbBPd@Hf@Hf@Jf@Jj@Lh@NTFRFh@Ph@Th@Th@Vf@Th@VRJRJf@VTJRHf@Tf@Th@Tf@Tf@Th@Tf@VTJRJpAl@f@Tf@Th@Vh@Vz@`@nAj@|@^f@Th@Tl@Vt@^pAl@jAf@VJl@V`@Rj@Tl@Vp@ZvAl@|Ap@\\Nh@VDBXLZNfAf@d@Rx@b@\\NfD`BxBbAjAh@z@^zB|@jGpClCtA`Ah@B@@@t@b@NJ|@p@d@^l@f@l@j@hBdBb@b@pArAfBdBLRNNJJfAfA^`@~A~ApDlDrArARRl@h@d@d@bAbA~@dArA|Al@t@~ApB`BvBx@`An@t@^`@XZv@t@r@l@d@^`@Zj@`@d@ZVN~@f@^Rd@T~@`@hBr@|CbAJDzAh@NF~@^f@Rb@TB@z@f@t@`@h@\\t@f@t@f@x@p@xBzAtEjD`BjAnA|@dAv@n@b@t@f@f@Xf@Zd@VTLRJZNl@Xz@^n@Xd@PrAf@XHNF@@~@VdBf@fAV`ARv@N`APh@HTD|@Jl@Fh@FTBh@DfCPh@BrDPvBJhLj@vALN@`AL`ANf@J`APj@N~@Vb@LfA\\~@\\fAd@t@\\|@d@t@b@nBnAl@d@z@n@r@l@x@r@bA`Ar@t@fAfAfAfAfAfAFFVTb@d@tAtAt@t@vAxAzAxAhAjAtArAfAfAbGbGnBnBp@n@^\\z@x@fA|@v@j@d@^lAz@fAr@p@b@xBvAjAv@dAt@p@f@j@f@t@p@\\\\hAfA|@~@hHzHjAlAvCdD^ZPRv@x@hAdAx@t@b@^VVr@j@\\VdAv@b@ZNLXRTPt@f@fBfAf@V@@FBp@\\RJ\\Pz@`@|B`AlAd@ZJJD\\J@?HDh@NnDdA`Bd@pCv@fF`Br@R~@VxAb@fA\\t@Tt@VfA^fA\\fA\\`Cr@tA`@`Cr@bAZp@TB?LDl@RJBVHZH`D~@XJRHh@Vd@Tn@\\|@d@x@d@fAl@fAp@XPl@^zC`BlAt@h@ZjAr@vBlAbAl@~ChBbAl@jCxA^Tn@\\\\P\\N^PZRPLRLZPr@`@dBdA`Al@NJx@f@TN^TzCfBl@`@h@Z\\RXLx@\\d@VVPj@\\RLZNd@Tj@\\`@TjAp@h@Zd@Vh@XjAl@^RZPPFRJp@Tt@XRHPJRHPFLD^Jz@RxA^h@NTFRDzB`@TFTDl@Jj@JtCb@|@P|@Rp@LrAXvAThB\\zBb@h@Jh@JfBZbARtAVh@HpATVFpAX~@TrA^|@Xf@Ph@Pz@\\VHd@TnAj@|@b@jAj@^RXPv@d@b@Z`BnAbAt@n@b@TP@@BBPLj@d@tAdAbAx@|AlA~@t@bFtDxAhAbAv@d@\\f@^|AdAbCdBpEvCdCbBjD|BtBvAhGbEjA|@pGhFb@^b@^hBbB`CbCZZ^`@fAhA`AhArA|A~@jAv@`A~B|Cr@`At@lAl@~@z@pAx@pAxA`ChArBbAhBf@bAXj@tBlEZp@~BhF|BjFpBnEjAlCXn@Tj@bArBpAbCl@`A|@tAz@jAb@j@l@t@p@v@r@v@bA`Ab@`@b@`@v@n@b@Zt@h@RNb@XvBnAnAp@nAj@pHxCtLxEjIfDTHfHtCNFrBx@\\PzAt@jAp@bBfA~ArAl@f@pBjBNLx@t@jApAhAzA`AvAf@v@x@rArAfC\\t@LVP^d@x@fF~JhBjD`AnBxFxK|BpEp@nAxBjEjA|BFH?@pBzDb@z@j@fArAdCdBfDh@fAb@x@JR`@r@\\l@LTNTZd@`@j@PVTVNPRTt@v@' },
                  start_location: { lat: 41.7479184, lng: -72.659972 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '30.2 mi', value: 48629 },
                  duration: { text: '28 mins', value: 1674 },
                  end_location: { lat: 41.2370319, lng: -73.14474109999999 },
                  html_instructions: 'Take exit <b>17</b> to merge onto <b>CT-15 S</b>/<b>Wilbur Cross Pkwy</b><div style="font-size:0.9em">Continue to follow CT-15 S</div>',
                  maneuver: 'ramp-right',
                  polyline: { points: '_co|Fzkc{LBJDLPRTTl@n@RTZ\\\\\\n@l@Z\\d@f@n@n@ZXTRJJZRVLPHVHTFXFVBX@V?Z?f@Ef@Ef@EZC|@?`@?V@Z@`@B@?PEx@Nj@JZFzAXn@LdDj@v@Lj@J\\FVDjCd@|@NtB^~@Tz@Tv@V|@XjA^XJZLf@Rt@Zh@Th@Tt@\\x@b@fAl@PJVN|DfCdBjAz@n@r@h@r@j@r@l@|AtAb@`@`@`@PN`@`@Z\\VXJJFF\\^^d@`@d@TVX^RV^d@RT\\d@PTVZV\\RVTXTZVZV\\PTXb@RV\\b@PTZb@X`@X\\PTTZPVTXZb@PV^f@HJDDPVZb@PTNRLNHLDFNRPRNR^h@b@l@Z`@JNBF\\b@^f@BDDDX`@\\d@^d@^f@^f@d@p@j@t@f@n@b@j@PXb@h@LRLP^f@PTxBxClE~Fx@fANRZb@b@j@JPd@l@r@~@h@r@b@j@nAdBf@p@dAtA^h@Zb@`@h@f@r@h@r@\\f@\\f@PTDHHJj@v@\\h@^h@^l@j@x@j@|@^j@^j@Zh@f@v@^j@`@n@b@r@j@x@f@v@n@`Ah@|@d@r@`@l@V`@Zf@Zf@\\h@\\j@^h@Zf@PXT\\T\\RZV`@NTZh@RZRZTZBFBBDHPV\\j@Zd@`@l@LRZf@PXBDn@~@`AzAhAfBtAxBb@p@b@p@v@lAjAjBZd@~@xAT\\@Bp@dAXb@p@bAfAdBp@`A~AbC`BjCJLPZn@`Al@`A^h@b@r@d@r@tAvBb@n@Zh@HLf@v@T\\rClE~@xAVb@nBxCl@~@DBJP^f@l@x@`@j@`@h@n@z@TXRVX\\VZrA|ARTTV~AfBp@t@fAfA\\Zd@b@h@h@ZZ\\\\|@x@`CvBZV^ZnAbAd@^b@Zj@`@l@d@xAdARL`@V~BjAlCxAvBlAdDdB|@h@l@XzCdBv@d@TL@@`@Rz@b@fAh@bE~B~@d@hCtArBbAxAv@~A|@hAn@hAn@jCrAr@^fB~@hBbAxAz@v@d@b@XtCvAjB`A|A|@nJbFVNbAj@|Az@\\P`B`AJFt@b@@@bBdAXPlBnAtB|Ar@j@lDrCz@t@NLDDFFb@\\`@^xArAv@r@v@p@\\Xj@d@d@^j@`@`At@j@^f@ZvAv@f@X`Bt@r@Zf@Rh@R^JrA^fA\\dA\\tFfB~@XdBh@v@VjBh@ZJRFnBl@`AZr@RtAb@h@R`@Pf@R`Ab@v@\\jAl@|@f@bB`AjC~Ax@d@xBrAlAr@~ClBtAx@lAr@vBpAhNjInAp@TLl@X`Ad@dAd@bA`@~Bz@pBt@dBn@vAh@rBt@`A^~DzAfA`@F@|Aj@pCdAnAd@dBn@~Al@t@Vh@Pp@RrA\\|@Rl@LbAPxB^rARdAP~@NjARxATr@LbAPtBZpATxAVlC`@fBXnB\\rCb@|Cf@jMrB`APtEt@bBXzAVr@Nj@Jl@Nv@Rn@P|@XjBp@`@Nd@Px@^bDxApFbClCnAvB`AdBv@bBt@dBv@xBbAxB`AhClAx@b@|@f@ZRl@^f@\\|AdAd@^dAz@d@`@xArAt@t@p@t@tCdDdCtCdBlBzHbJ`@d@dJnKVX|@dAlAtAz@`APTrAzAtCfDrB~BZ^vEnFRXTTpA|A`AjA^f@j@~@Zj@P^z@fBNZzA~Cp@tAnAjCh@fATh@PXXl@Vh@Zl@nAjCnAhCzA|Ct@~AVl@L`@Vn@Tj@Vr@Xz@Tp@^jAPr@VjAt@rDt@zDf@nCX|AVxAj@zC`BdJd@dCn@fD\\hBNt@F\\HZPr@Pn@HZJZHTHVVp@Xr@Vh@JV\\l@Zl@Xf@BF\\n@lA~BdAlBfApB`BzC\\r@`AdBh@`Av@xAh@`A|BdEb@x@BDLVR^p@nAx@|ALRZl@t@tA`@v@d@z@LTLTLTNTh@~@\\j@NRLTNR^d@PT^b@PRNP^`@PRPPPRNNNPPRNNPPPPNPPRNPPPNPPPNPPPNPPPNPPPPPNPPRNPPNPRNPPPNPNPPPPPNPPP`@d@NNZ\\v@z@~EjFp@t@r@t@`@b@`@b@`@b@bAfAbAfAr@t@r@r@`@b@TXd@b@PRb@d@p@t@r@t@|@`AZ\\NPNPPTLPVb@RZLV?@FLBDJTLXJXFL?BPh@HZ@BNh@Ll@Ln@NvAD^Dj@Bf@@Z@^?x@?xA?H?r@?tB?^?v@?rC@Z?Z@^@Z@\\BZ@\\BXB`@JnAD\\B\\DXHd@Hl@HZPr@HVDNBJTr@JXHTVn@Zn@JRZj@LVNXVd@NVVh@hCxENXt@tA\\n@h@bAt@rA\\p@Xj@Xp@p@~Al@bBRp@Rp@Tr@bAjDVx@Rr@Tr@\\hAh@fBf@bBL^FRHZPl@zDpM`BhFn@|BDLt@fCx@lCDLd@~A~@|CjBrGHXHXJd@j@tBFRJ`@FVFXPr@FXFZFZFXFXFZDVBNPbADVF^DXFZDZ@LBL@JHj@Fh@Fl@NnADZBXD\\Hv@LpAHx@BZDZBZDZBZDZDZBZDZBZDZBZBZD\\BXD\\Ht@BZD\\Hv@RlBn@nGJ|@PnAN|@Lp@Lj@Jb@FXFZHVHXL`@HZHVJXDLRn@LXJVJVXp@Vj@R^@DXf@T`@LRLTX`@LTTX\\d@TX~BnCnB~BtChDbBnB~HpJn@v@@@n@v@t@z@`GdHbGdH^b@l@r@v@|@l@r@d@f@~@fAb@h@`@b@n@t@r@x@`@b@n@t@p@v@rA|AbAhAp@x@`AjAbAlAl@p@j@p@nElFl@p@x@`AXZVZ~@hAvErFbAjA`BnBfCzClA|A`@j@`@j@l@r@rB`C`BlBt@x@fDjD^`@^b@rA~AlDxEnAbBnAfBxBbDhCvDjBnC~@rAz@nA^h@l@x@nAbBRZpEzFvLlOlA`BlAfBj@|@hAjBf@|@\\l@Xl@`ApBx@jBN\\DR@BDPDLJX\\x@Vn@HXVv@z@nCf@dBPt@b@fBf@bCn@bDLt@Jt@Lz@x@xEv@~EzAdJrAjIn@pD`BdK`B`K~DhVTrA?@XbBr@jEt@vEj@hDv@vEb@jCRpANr@Pr@FZZnAHVTt@HTJZJZN\\L\\LZTf@Rb@NZRf@Tb@^l@\\j@JPLPLNNTPPlArAn@p@XXPNLLVR|@r@v@j@XTTNJHLDZNr@Zj@R~Ah@l@Rh@ND@LBXF\\FB@F@JBJ@`@Fv@HtANn@Hz@Nt@NlBTxBVnBVzBXjIvAhEf@fGz@~@LnAPtEx@|Cp@zBj@jExA`DnAtExB`CpAjDtBbDzB|D`DhB`BXTrExD^\\nBbB\\Zn@f@hA`AfA`AjA|@r@l@n@n@nB`BpD|Cd@^x@r@XVn@l@l@d@n@j@|AnAnAfAj@d@`@Z^Z\\Zr@r@fA~@pAfARNd@`@xArA~@t@p@j@vCfCFD|BnBFFDDJHv@l@pAlAzAtAvArAlApAhFdFt@v@b@`@hAfAnBfBlAlAr@p@bDxChB~AZXdHbGxAnApB|AjA~@hCjBtBxA`C`Bf@^vAhArA`AjA|@h@^\\XfA|@xCdCxApApC~BhGjFdBxAb@^|BrBrAnA~A|AZZh@j@~@~@nBvBzAbBbAjAdApAnCjDNRPT\\f@\\b@|AxBlBnCJPx@lAdAdBb@t@j@`Ax@xA`AdB^r@NVf@bAZj@Zn@d@~@f@bAr@zAb@`Af@dAb@dAd@dAb@hATj@Tr@HTf@bBd@dBXlA^hBZjB^hCPpADb@BNHz@RrBNbCJlBFhCBrA@ZDjC?^D~BFvEFdEDxDD`DFlD@zA@`@FxEBdA@rAJpCDv@HtAHpAHz@TdCJx@PrAJx@Lr@Pz@b@|BBNH^ZdBH^^pBHb@TlANx@d@dC^vBjAdGP`AJd@RdAF\\d@~B`@rBZbBF^XtAZ`B\\nB`@pBXvA`@zB^jBZ`Bh@pCl@zCZfB^lBVxAFXJj@n@jDf@pCh@jDN~@Jn@b@pCVbB\\zBHp@Ff@^nCRvAR~AXbCNnAd@`ENtADf@LnA\\lDXtCVdDFv@D\\BZ\\zERrCLlBRbDBh@V~ELbCNpDJbCJnCPnGBbABl@?RBv@@`@JzEFdFFzE?X@|B' },
                  start_location: { lat: 41.5340816, lng: -72.7674986 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.6 mi', value: 1029 },
                  duration: { text: '1 min', value: 45 },
                  end_location: { lat: 41.23524219999999, lng: -73.1554199 },
                  html_instructions: 'Take exit <b>52</b> for <b>State Route 108 S</b>/<b>State Route 8 S</b> toward <b>Bridgeport</b>',
                  maneuver: 'ramp-right',
                  polyline: { points: 'mbuzFram}LEPA@?FAHAXAt@CtBC|@C|@CTGj@Gh@Mx@I^Ib@Kb@Mb@g@lB?TA@?@?@ADAHCFCRCPCLCPAF?HCNALAN?LAVAN?JA`@?J?N?J?D@H?N@P@NDd@Fn@BZD\\BPDTBRBPDRH`@FVLh@Nh@Nl@@BRl@BHDLPb@FPJRJTNXLTBDLPHLPVJLLPLLXZXZFH^^JJVTNLFFPJNLTNTN' },
                  start_location: { lat: 41.2370319, lng: -73.14474109999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '5.2 mi', value: 8446 },
                  duration: { text: '5 mins', value: 303 },
                  end_location: { lat: 41.1732676, lng: -73.193737 },
                  html_instructions: 'Keep <b>left</b>, follow signs for <b>CT-8 S</b>/<b>Bridgeport</b> and merge onto <b>CT-8 S</b>',
                  maneuver: 'keep-left',
                  polyline: { points: 'gwtzFjdo}LJFBBB@FDFBRNh@`@NNz@l@f@b@b@ZXRrA~@xAjAZVRPDDB@BDz@j@~AnA^ZPLt@l@v@l@HHFDRPl@n@^`@RVZ`@T\\RZBFLNR`@rAvBj@`APZHRhAhBd@t@x@tA~@xAx@tA`@t@DFDHFJDDDBHBb@x@Vj@Vn@Zn@Tl@Vp@L^J\\Ph@\\lAd@dBVhALt@P|@pApHrAfHh@tCh@tCLt@VnAr@|DNv@TpA^jBb@fCv@jELt@FV?@?B@@@LJd@Ln@Nn@Rt@HVN`@Pf@Vj@Xl@f@z@T\\V\\^b@f@h@^\\XVPNPLRLPJVNXNd@TTHb@NTFZHf@Jj@JpBVrAR\\D`@Fz@Pv@NlAVpA\\`@JLDHDB@B@DBDBBBHHx@Xb@NRJb@Pf@RTJNHb@Tv@`@t@b@l@^j@^b@XdAt@bAt@`Av@@@ZV`@^`@`@XZTZTXPTTZXb@Xh@p@jA`@t@t@rAR^d@z@R^`@p@Zd@\\f@JNPRZ`@TTRTZXPP\\\\NJLJJHZTVNNJRLRJRLPHPJRHRHd@PTJ|@\\d@RJBlA`@XL@@\\L@?f@RNF^Nd@RPFb@RfGzBfCz@zAh@rBl@ZJ`@Jb@LLBPFNDVHTHVHd@LTFJBFBJBFBNDD@`D~@lBh@XHbAXfAZfAZt@Th@NVHHBrA^rA^`APRD`APj@Fj@Bd@Bl@@n@?TA`AEh@ENCZCh@Ij@IPCXGXIh@M|Bo@r@S^KhBi@pBm@\\KPEr@Sj@QNE\\Kb@K~@Yf@O@?z@Wd@MXGj@MTGj@Ib@GDAb@EH?\\CJAh@A~@Al@@N?R@B@B?F?L@d@Dj@Fp@HXD^HdARtAV`ARj@JRDfB\\\\Ff@HhB^`ARn@JPBhB\\j@Ll@Lf@Jb@Hb@Hb@H`APjB^dARz@P@?RD^Hr@J\\FLBNBXFh@HTDb@DH?L@J?F@B?V?f@?\\APATCPCPAPCHA@APCJCLCNEh@OTITKZM^Qd@[NId@]POPORSPSFEX[RUX[PQNQ' },
                  start_location: { lat: 41.23524219999999, lng: -73.1554199 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.2 mi', value: 350 },
                  duration: { text: '1 min', value: 19 },
                  end_location: { lat: 41.1705391, lng: -73.194378 },
                  html_instructions: 'Take the <b>Interstate 95 S</b> exit toward <b>N.Y. City</b>',
                  maneuver: 'ramp-right',
                  polyline: { points: '}shzFzsv}LXUBCDCFGVSHGJGJG@?HCJEJEHCJALCFAJAF?DAF?F?P?H@H?J@NBF@F@B@F@HBFBNFHDPHLH@@PLLJDDJHHJFJFHFHDHHJDJHPDLDJ@BBBBBD@DB' },
                  start_location: { lat: 41.1732676, lng: -73.193737 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '29.4 mi', value: 47357 },
                  duration: { text: '28 mins', value: 1694 },
                  end_location: { lat: 40.9884973, lng: -73.6663556 },
                  html_instructions: 'Merge onto <b>I-95 S</b><div style="font-size:0.9em">Entering New York</div>',
                  maneuver: 'merge',
                  polyline: { points: '{bhzFzwv}LRp@Pp@JZDPFTf@dBXdATv@bAnDRt@J\\b@vAPp@Pn@DJTz@Tv@Pr@Rr@Rt@b@zAFPh@dBV|@V~@^zANr@Nr@TpAJv@PrAJv@B\\Fl@Db@Fv@BVB^Bf@Bj@HpBFtAFvADx@Bz@DbA@R@ZDx@FvADfAFhADfABt@@b@?DB|@?Z?pA@`@Av@Cx@Af@ARCXA\\AZAN?J?DE~@ATc@rKQnECr@Ex@?HAXCTM~AEh@Gh@Kz@Ih@Kn@Mt@Or@Qx@Ot@IXOp@UfACJQ|@Kh@Ot@Ot@Mx@AJIj@E\\It@C\\CXCZEx@EzACn@Az@?j@?J@l@@j@@v@Dv@BZ@XHv@LrAFl@Jf@DXDXFZNt@Nr@Pr@Rr@DRH^XdA|@rDbAfEx@bD`@~ARv@@FPn@x@jDRt@@DPn@b@fBTbABJRt@^zAZhARr@Rp@Tp@`@hAXr@Vl@Vl@b@|@N\\Vd@BDLVPXr@lA|@rA^h@l@v@|@fATVBBPTfBrBbBpB`AfAVZZZNPb@b@`@^d@\\`@XVPRLXPXN@@XNb@PtAh@ZJF@D@d@LlARhANpANzANXD\\Bp@Hn@Hh@Hh@H^HXFl@Nn@Rv@Vv@Vt@\\f@TPJTJp@\\\\RZRTNZTj@b@b@^RN@@`@Zh@h@h@h@b@f@X\\d@l@LPPRLRj@x@f@v@d@z@`@v@Xl@Zn@Rd@Pb@Rf@Pb@FPHX^hANh@Rt@Rr@Nr@l@hC\\rAVbAH\\?@J`@~Ir_@H\\Ld@VdAfBxHdC`KF\\b@lB|@rD@DFVXhAXhAZxAZjAj@~BXpAVfADTJf@@JDPHd@NdAP`AHx@DZHj@Hx@H~@@LBRDj@Dl@F`ADfA@b@Bp@Bv@BbAFtDBlABzBLvFFhD?l@@D@r@BvBBrA@v@@dABvAFnC@x@Bx@@b@Bf@@LFp@Hv@Hv@DXJv@X|AJf@FZHZPr@Rp@DLNb@b@dAVn@Xj@Zj@Zj@z@rAbAxA~BnDX^DHRZJNl@~@NRHLTXV`@BFLN`@l@l@z@l@z@z@nA^h@z@pAFJd@p@FHFLz@lAxBbDn@|@\\f@p@z@NRLPZ^l@p@tAzATVDDPPjBpB|A`BvB`CbAfAbAfAp@r@d@h@pAtAhAlA|@`Ar@t@p@v@`@d@^d@^d@RVZb@V^b@r@\\h@d@z@p@nAz@lBz@vB`@jATp@Rp@JZBJV~@XlA|@xDz@vD|@xD`@hBf@fC`@dCl@bEF^BJHl@bAfHdAnHf@dDBPF^Jb@ThAd@jBPj@J^DJFP^bAx@xBn@~An@~AfAnCv@xB\\jARr@T|@BJH^d@fCFb@Hl@Hv@RpBDv@FtADvA@tA?z@CrBCx@GrAIrAQpBKv@Kr@Mz@c@|Bo@bDm@fD_@lB]jBc@bCEZG\\CRCN_@~CQ`BGh@YhC[bDu@zGQdBKbAMrAIv@A^Gz@OjDCv@CtA?z@?vA?tABvA@R@d@T~FHpBJlDVpG@ZXlHJnCNdET`GLjDLnDHrBHdCb@~KFlBJrBJpBJpBZzELzALrARnCJnADf@?FFn@BTFv@JtAJrAJtAFv@HnAF~@FrAHvADvAHnBF~A@N?RB`@@T@x@FvABz@FpBDrBH`CDhB@PFvBLrDJtDDtAH|BBj@BdADdB@`@FtBDx@B~@HbALvADf@Fh@Fb@D^Jn@FZNz@Lh@HVJ^ZfARf@d@nAn@xA~BjFbLjWlApCx@hBhAfC~@vBj@rA`A|BXr@d@nAbAtCz@tCn@~Bn@tCR|@RbALn@X~ATxA|@jFt@hEdAlGXzA^tBd@hCVlAd@xBh@tBt@nCRv@r@xBNj@j@nBjAvDv@fCl@vBNj@Ln@RfAX`Bh@lDNtAbBdLdBdL`@pCLz@Jv@Df@Df@HhAFbA?BB`A@J?\\@t@AlAMpHAv@Ad@Ad@CfBAh@AXAn@A`@AT?XCr@AdCBnABt@Dn@Bh@TdC@JFb@@DFh@TjABPDRLl@XlAXnAVjAT~@DRLf@j@fCZrAb@nBNr@R|@T~@FPVz@Rn@Rn@Xt@Tn@Vn@r@nBj@xAn@bBnCjHjCbHXt@FN\\|@b@hA^dAJTXr@z@`CVn@Vp@Vr@Vp@b@hAJXVl@Vj@LVJVnAbCTb@JNFJd@v@`@p@j@~@Zf@^h@`@f@^b@^d@^d@n@t@b@f@p@x@n@p@PTRRNP`@b@`@b@b@f@^b@b@h@r@x@~@dAdAhATXXZV\\LNNNPTZ^VVNPNPd@f@LPPTPPPR^b@b@f@XZVX\\`@NTT\\V^\\l@Zj@\\l@LVHNJTLVFLBFJRJXJVJXHXl@jBPp@Rr@ZpAZnAd@pB`@~AZpAH\\ZvAXhAFZH\\Pj@Tr@Pf@BFLZXv@Tb@LZZj@Zn@Zd@V`@V\\^b@PR`@b@`@b@t@r@d@\\d@\\PLd@ZvBlA|@j@~A|@vAx@v@b@z@d@z@d@bB~@z@d@dBbAlAt@pAr@z@d@`B~@pAt@dAl@zAz@|@d@|@h@|@f@lAl@bAh@ZP|Az@b@Xd@Zf@^TPLLRPTPz@x@h@n@Z`@b@j@V`@\\h@hAxBt@lB^dAVx@Jd@Lb@P~@\\dBTrA@@TrA|EdXPdAZdBn@hDV`BPfAL`AVtCXlGH`BPpDHnBFvAHfANfB^`DRdARbAZpARv@Vz@ZbAfHbS`@dAV|@XbAXlARhA@HLv@J~@Ht@LzAHdBBfA@hAAfAAr@SfGCp@_@~KK`DCdBAdA@nA?LFlBFpAJnANtARvARlANr@VjAV~@h@`Bd@nAj@rAj@dAh@`Aj@z@`@j@f@l@f@j@fAfA^XtBhBfB|AfBzALJLHbIzGd@`@p@f@`@^@@`@ZfA|@~ApAjA~@dBnAzAjAn@j@b@d@@@r@v@~@bAj@x@`@l@j@bAb@z@h@pAb@hAb@|A@DV~@VlALj@DV@Lt@nFbA`J~@bI@LBLFn@ZtCJ`AD^^hDPzAHr@ZnCXjCNrAL|@@HJl@Lp@@FPt@Nr@Nj@Tx@h@vAj@xAZn@\\n@z@xArA|BVd@T^r@rAVh@PXh@jAv@lBj@xA^lA^pANh@\\rAr@`DTbABLPx@ZjAX|@vA|Dv@|Bf@bB\\rAHVPv@TjA^dB\\fB`ArEj@nC?@BHDTz@dEz@bEd@~BLn@?BVjAXxAt@pDtB`KnAjGNv@?BVrAN`AJx@Jr@Dd@Dj@Df@FnA@HBb@FzB@rCA|@Az@GrACt@MdCObDGvA?@G|AMbCUnFC^[jHIdCGdD@|DDbC@\\DhAFpA?@JdBNlBJbANtANlAJp@XhBVtAd@xBd@lBn@vBb@vALZXz@rAxDnAtDBF@B@Dj@~Af@xA|@nCf@pBTdALn@F^TxARvABT?@^hCrAbKNhArApJ?@F^FTRfAb@rB\\rAlChJ?@?@BHb@zAbB~FnA`E`AhDp@zB|CpKx@vChAtD^dAn@~A@BXl@n@lA^n@d@t@n@|@b@j@b@f@\\`@TT?@v@t@x@r@vAbA`CfBjDbChD`CzAfAB@x@l@\\XVTPNBBJLZZX\\f@l@l@z@NRLTf@z@Rb@\\r@^`ATl@Z|@Nh@Lf@VfAp@tDHh@Z`BV|A~@dFz@tEr@bDZlAh@nBL`@Nj@X|@^dAp@lBpAxDbB`Fn@hBh@dBVx@~@nDvBjJR|@HZ?@@BFZnAtFf@xBx@lDfA~EJb@h@bC\\xA?BDTb@hB^hBPhANbAF`@@JHx@JpAHnADx@D|ADbB@`@N|ED|AF~AF`ADb@LrAL~@Fb@?@N~@Np@R~@Rr@Pl@Tr@Xv@Tl@Vj@Xl@T`@Xf@V`@V`@b@j@|@hAnB~BjBzBhB|Bb@d@l_@fd@jBxB^b@~@jAfD~DjAtAh@l@j@l@l@j@h@d@h@d@tAdAdBjAdBlAhBnAvA`AzB~A\\TvA~@rBzAj@b@`Ax@|BpBZZj@l@JJj@n@fDrDb@j@d@f@TVj@n@\\^@@l@n@\\\\X\\TTb@d@VXZ\\ZZX\\VXTVZZ`@d@\\^LL\\`@\\\\Z\\PRn@t@hAjAl@r@NPf@j@^`@h@l@d@f@t@x@~AdBjApAfAjAf@h@f@h@|A~AhEvEf@j@zAbB|AbBf@j@~@dAr@v@p@x@f@t@v@tAHNZt@' },
                  start_location: { lat: 41.1705391, lng: -73.194378 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '15.6 mi', value: 25129 },
                  duration: { text: '16 mins', value: 946 },
                  end_location: { lat: 40.8370699, lng: -73.8252993 },
                  html_instructions: 'Keep <b>left</b> to stay on <b>I-95 S</b>',
                  maneuver: 'keep-left',
                  polyline: { points: 'cqdyFv}r`MZl@Xt@Tt@Tt@Rv@Pt@Nv@Lv@Lz@H|@Hx@Dz@D~@Bz@@z@?z@Az@C~@Ez@En@GzAI|Aa@lIEv@Cv@Cv@Cl@Az@Av@?z@?|@@z@@x@Bz@Bx@Dx@Dx@Fv@Fx@JfALdAFn@Lx@Lv@Nx@Lr@Nt@Nr@Rr@Pr@Rr@r@`CVx@Xz@Vx@@DPr@Nd@|@~Bp@|A\\n@pA~BpDrG`DzFNVlCzElCxErAbCBFVb@`BtCx@zAdBvCt@nAx@jAfDdF^l@LTfAtBn@vA~@vBp@bBJTFLh@rAjBpEv@nBf@zAV|@\\nAj@nCVvAHr@NdAVbCH|ADjADpA@H@Z@~@?nBAv@CrAIjB}@pPQ`D_@|GIxAAZGhBEnBCfBAvA?bB?@B|CBzAJdCJhCLfBJjAD^LjALx@TbAVhATx@Tt@`@hAf@hA\\n@h@|@h@v@p@|@r@t@t@r@p@h@j@^\\Tb@TTJd@PRHj@Rv@TbInB|@Tr@PlAd@rB|@|Ax@dBjAjAx@h@f@tBvBh@p@h@r@dAxAfAdBp@lAj@fA^|@P`@`AdCd@zAj@xBf@xBl@~CfAxF`@zBb@~Bh@nC`@bBb@tAZt@FNBDP^HP`A|Ad@l@d@f@n@r@b@`@`@VxBhA\\Jl@TlA\\t@Rt@RVFbCl@^H\\H^Jd@Pf@Rp@Z`@Vb@VpBzArGfFnIvGh@^DBHH`@VPN`BtAv@h@n@b@r@\\|C~AnDbB`Af@|@f@~@d@NFPJlAl@lAl@RHhAl@dCjAv@\\VJx@XJ@RFfBVXDlBXzAXb@LVFv@ZbAd@l@ZnAx@v@p@jAlAfF|FfNrO~EzFjAxARVFDRTn@z@LNjAxAhC~C|BfCh@p@n@v@pCdDzCxDdAzAjA~AXf@b@t@Zl@bAtBVl@Xx@Xx@BHbAjDLl@lAbEx@jCJVZt@Rd@DHT^\\j@PTTXDDd@f@VTXTTPPJPJ~@f@fAh@pAl@b@Vh@\\j@b@`@\\\\b@d@j@Zd@HJn@`AZh@~AdCrB`D|@xA|CxEx@nAhAvAd@h@vBzBlCfCPPh@h@p@p@h@n@NRJJb@h@p@~@d@t@|@rAf@r@p@|@\\f@LLLLPT@?JLTR^ZPR\\V^X@?BBTNXPRNv@f@`@VrDdClCbBt@f@TLDBHFLJLHNJFDDDj@XPJTJNFNHj@Rb@Nt@TvBl@VFHBdAZbA\\BB@?ZNB@RNHFXPjAz@`@`@bAdALNRXT\\FNJNNX`@x@Vj@\\|@Pj@d@xAVt@Vt@LXVn@LZFLLRZj@V`@Zb@TZDFNNBFPPRTHFDF\\XRNLJNJLHZP\\NZRB@PHRJv@`@|A|@n@^x@h@b@Vf@\\f@\\jBrAb@Zx@n@NJFFJFPLnB|Ap@n@lAfAh@d@TTn@f@b@Xb@VTNTJVLh@Tj@RhA^JDnBl@hCt@TDt@XlBv@xB`ApB|@`A^PHjKzDlAd@n@R|B~@bCdAz@b@FBr@\\lAl@nAn@^R|DtB`Al@\\V`@Zt@p@h@n@d@n@p@fAh@dARf@N^Ld@DHRt@Lh@TjAJn@LdAHt@B\\Bb@@r@Bn@?t@Ar@C~@Ch@En@Gn@Kz@OlASbBKx@KfAI|@InAKjBEhAGxBCtAAzA@bAAXBz@@d@@\\BnABd@B^@Z@H@TDh@BNHz@LfAHx@N|@N|@^xBP`ATjAt@rEh@~CNr@@J?@F\\n@~DDNJn@BNNx@ZhBX`Bj@dC`@bBXhAZdAPh@FPn@nBnAnDd@pAd@lArA`DR`@P`@p@tAFL|@dB`A|ApAjB|@lAj@r@r@v@~@bAf@b@b@`@vAlAbBjA\\VXNd@VXLrAt@~Ab@pCj@p@F`AHf@B`@@`@@f@?z@Ax@AzAKl@GbAI^ErASdASnA[xF_BpAg@`Cy@jBs@|@]VKZMDA^O`@OJEv@[tEoB`EiBxDcBnAg@h@Qv@YdAYvCcAl@U\\Q^QNI^W@?d@[jA{@j@o@~@gA~@iA^c@^YJKLIXQXOXKf@MZE\\IJCNCj@Qj@QXK\\K|A]j@K`AOx@KF?h@G|@G@?@?XC`@Eh@EbBKD?lAGdAC|@Cr@AV?Z@`@@`@B`@Dl@H@??@^F^HZHtGzAtAZf@Jj@Hh@Fl@Dh@Bj@?j@Aj@Ah@En@G?A`@E`@Id@Kf@Od@Oh@Qd@Uj@WpB_AFEh@Sf@OXINEh@Mh@Ij@Ij@Eh@Cl@Av@A|HGrXU^Af@Ah@ENAFAj@G`@Ih@Kf@Mj@Q' },
                  start_location: { lat: 40.9884973, lng: -73.6663556 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.6 mi', value: 1044 },
                  duration: { text: '1 min', value: 46 },
                  end_location: { lat: 40.83042770000001, lng: -73.8328202 },
                  html_instructions: 'Keep <b>right</b> at the fork to stay on <b>I-95 S</b>, follow signs for <b>Triboro Bridge</b>/<b>Geo Washington Bridge</b>',
                  maneuver: 'fork-right',
                  polyline: { points: 'u~fxFb_raMtAWVERCRCVAT?T?T@RBTBTDTDRFRHTJRHPJRLPNPNPPPPLRPTHL?@DDJRLTJTVp@tCpH@BPd@Rb@LVP\\Tb@Zj@Zj@jCzEf@~@pAfChBhDNZN\\' },
                  start_location: { lat: 40.8370699, lng: -73.8252993 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '4.7 mi', value: 7524 },
                  duration: { text: '7 mins', value: 390 },
                  end_location: { lat: 40.8049873, lng: -73.91138750000002 },
                  html_instructions: 'Keep <b>left</b> at the fork to continue on <b>I-278 W</b>, follow signs for <b>Robert F. Kennedy Bridge</b>/<b>Manhattan</b>',
                  maneuver: 'fork-left',
                  polyline: { points: 'euexFbnsaMLJLXLVJVHTLXHVPf@HXHVHXHZHVFZHZFXDXF\\FXDZDZJXD\\DZFd@BP@N@@Df@Hx@BV@H?B@J@N?@@VDn@@TBd@@v@Bx@@x@FdG?x@?@@X?@@\\?B@v@Bz@@L?@@f@Dx@Dv@H`ADr@Dl@Db@@H?D?@Fb@Hx@Fj@?B@J@@?@Hr@LhADb@?FH~@XnBJp@@DlApJLrARrBFx@Hx@HlADh@T`DRjC`A~MJhBhCl_@Fn@d@rHHvALpBLlCPjEBn@DdA@f@Dl@^vFVlDFt@@R@J@P@PFp@l@`JPnCPxCThDFt@@XB^h@zGB\\JrAVxDVfDHtAHjADt@Dj@T|CF~@X|DBZt@nKDv@Fv@Dv@F|@Dr@Fz@J|AJhANzAHbBFtAJjAL~ABRDd@?@?B@F?HHZBHBHVj@lAnBvAdC@BLRP\\t@nALTPVTZPVRZRVPPNNh@n@XX`@d@f@f@d@d@VX`@`@d@b@VTTRTRzAxA`B`BDBhBjBn@f@l@n@xBzBlBrBxAxAvAzAfAhALLPPPTPPNRLPPTLPNTJPNTn@bAp@dAjGpJjGrJNXNVhFfI|DdGx@tANTFLJNFNFLHPHNHVHRJXFTfBvFTp@Rr@Rn@Rl@Tp@~DdL' },
                  start_location: { lat: 40.83042770000001, lng: -73.8328202 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.7 mi', value: 1113 },
                  duration: { text: '1 min', value: 73 },
                  end_location: { lat: 40.7980526, lng: -73.91970359999999 },
                  html_instructions: 'Keep <b>left</b> to stay on <b>I-278 W</b><div style="font-size:0.9em">Toll road</div>',
                  maneuver: 'keep-left',
                  polyline: { points: 'ev`xFdybbMlA~C^hARl@JXl@dBXv@\\`AFNBJDNBNDLBPBPDR@PBR@T@V@TB`A?P@NBN@LBLDLBLDJDHDJFHFFFFFHJFHBHDHBHBH@J?L@L?J@H@J@H@JBLBJDFDLD\\XrA|@p@b@dC~AzFtDfAp@fD|BPJ' },
                  start_location: { lat: 40.8049873, lng: -73.91138750000002 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.2 mi', value: 300 },
                  duration: { text: '1 min', value: 31 },
                  end_location: { lat: 40.7982231, lng: -73.9226152 },
                  html_instructions: 'Take exit <b>46</b> toward <b>Manhattan</b>/<b>FDR Drive</b><div style="font-size:0.9em">Toll road</div>',
                  maneuver: 'ramp-right',
                  polyline: { points: 'yj_xFbmdbMjAdADFBDDJBJDHBPBH@L@L@P?L?LAL?NANAJALALCJCLCNELGNELAD]bA[bAo@p@' },
                  start_location: { lat: 40.7980526, lng: -73.91970359999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.4 mi', value: 643 },
                  duration: { text: '1 min', value: 68 },
                  end_location: { lat: 40.8010139, lng: -73.9292926 },
                  html_instructions: 'Continue onto <b>New York State Reference Rte 900G</b>/<b>Robert F. Kennedy Bridge</b><div style="font-size:0.9em">Toll road</div>',
                  polyline: { points: '{k_xFj_ebM}@|BWl@M\\K^a@lA[rAQl@Ql@Sv@Sr@Qj@Qp@Sn@i@~AmEfNCJ' },
                  start_location: { lat: 40.7982231, lng: -73.9226152 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.4 mi', value: 715 },
                  duration: { text: '1 min', value: 49 },
                  end_location: { lat: 40.797215, lng: -73.9293301 },
                  html_instructions: 'Take the <b>F D R Dr S</b> exit on the <b>left</b><div style="font-size:0.9em">Toll road</div>',
                  maneuver: 'ramp-left',
                  polyline: { points: 'i}_xF`ifbMMd@k@fBIXGRGNCNCLCJAN?J?J?TBRFRBFBFFHHLJHDBJDPDP@J@REPIPMJKHMLYJW|@wCNWJQDGFKJIHIJILGJELELCNE~@En@ExCOr@CPAT?dAB' },
                  start_location: { lat: 40.8010139, lng: -73.9292926 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '8.8 mi', value: 14170 },
                  duration: { text: '14 mins', value: 821 },
                  end_location: { lat: 40.7015083, lng: -74.011977 },
                  html_instructions: 'Continue onto <b>FDR Drive</b>',
                  polyline: { points: 'se_xFhifbMT?H@N@P@P@NBPBNBRBNBPDNBNDPDPDNFPFNHNFNHNJLH\\TNJNJLLLLLLJNLNJNHPJRHRbCpF\\v@t@~ARb@Vh@Rb@Vf@T`@Tb@T`@Vb@Vb@X`@x@vAXb@X^V^Z^ZZVV\\ZZV\\V|@n@`Av@h@XNJNJNJNFNHPFNFNHPDNFjFfBPFNFNFNHRJRLPLPLPNRNNNjEpDNNRNNPNPNPNRLRLTFJHPJRJXhBrEfAlCJVLVJTLTLRNTNPNRNPNNPNPNRLPLRJPJTJRHTFRDRDTDTDR@P@N@P?P?PAPARANAPCPChBYPCNCPEPCNEPEPE`@KLERG^Ot@UtDwAPGNEPGNEPEPENENCpAWh@MVGpAO^ENAPANAL?L?N@L@NBPBNBLBNDNFLDNFNFJFNFLHNJNHNLPLPNNLpF|ERNRRJHLLJHJLJJJNLLPRJNLNx@jAZj@NVLRLRJPJNLNPTLNLLRR|@v@|AtAPPHHJJHJLLJJNN~@x@zAtARRPNLJf@b@f@\\NH~@n@LHJJLHRPzBlBVTHHJHLHNFJHJFXL`CrB`@^NLPNNNPNRPRRbBxA|ChCtAjAbBxARNJJPPPPPPLNTV~E~FHJ^h@xBtDHNR\\NRPRNPNPPLRPPLh@\\ZT\\RXRVPz@h@lBpANJLHNLNN|BpB`At@bAr@RLRNTNPLRPHLJJHLtApBPXNRPTTTRRTR`CrBtBbBRRVRZ^VVTVxDlDXTPPXTfVbRZT|AlA\\V^Z^\\Z\\^^hBlBZ\\\\Z^^d@^b@^d@Zd@ZRLf@ZZPZPzBnAb@XRJRJHBJDVJLFTHRHTHRFTFTFTFTDTDTDTBTDrDb@t@J`CVXDNBTDXHf@NRHTJPHNHPHPJNJrA|@pCfBb@ZVNLFTJRHTHRFRDXDT@RBT@N?F?T?RCRATETEVEr@MhDk@xB_@xB_@TE@?TEVEB?FA`@GrB]TGNC\\MVMBA@AZM\\WRQTUPSNQl@y@p@{@TY\\_@HIFEXSXSRKRITI`@KZGXEPATAX?T?f@Df@Bp@FzBPh@D`@F\\F^J\\Hf@Rf@Td@RVLb@TdAj@p@\\v@b@`Ah@xAv@`B|@d@VTLRJRHPHTHRHTFRFTDTDRBVBRB~@Fv@DxHb@h@DXBN@b@@n@Dn@Hh@Fh@Hj@Jh@Jh@Lh@Nf@Nf@P|@`@h@Tv@\\|@\\t@VfLxElBx@RHPHRJJFNLVPNLVT\\`@LPNTJPLTJTJTLZFPJZPj@FVLz@BPBR@L@R@TBX?TDlAFtBDnAFfADnB@ZDnADnAFhB?FB\\?J@D@RTfELtBP~CNfC\\dGDl@Dn@L|ALxAT`DNbBJlAXnDH`AFdAFhAL|AFpAN`BFn@Dp@Ft@Dl@HhADj@B\\Fh@BVDXDTFZHZHN@DDHDPJZJ\\FNDLXl@LZJVLRHPJTHRFLJTTf@f@nAXx@Tn@Rh@b@~@b@~@Vh@P\\P`@R^JTJVLVJRJRLT|CtF\\j@Zj@z@|Az@|A\\j@Zl@NVNVLTLTNXJRJRJRbBbDf@bAb@x@f@`AZd@FJDHDJDJDJFNDLDNBJDLBNBNBLBLBNBLBRBR~@`H' },
                  start_location: { lat: 40.797215, lng: -73.9293301 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.5 mi', value: 871 },
                  duration: { text: '1 min', value: 70 },
                  end_location: { lat: 40.7066222, lng: -74.01597749999999 },
                  html_instructions: 'Continue onto <b>Battery Park Underpass</b>',
                  polyline: { points: 'molwFzmvbMb@|CDXBT@V@L@N?H@N?N?RAP?PARARAVCPAVEVCPGTGTIVIRIRIROROTSVs@j@QL_@RC@A@QFA?UHa@L{FzAIBKBK@I@K@K@K?eA@G?K?I?IAIAMCKC{C}@KCMCMCk@OUISK' },
                  start_location: { lat: 40.7015083, lng: -74.011977 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.5 mi', value: 725 },
                  duration: { text: '2 mins', value: 149 },
                  end_location: { lat: 40.7129366, lng: -74.0139476 },
                  html_instructions: 'Continue onto <b>NY-9A N</b>/<b>West St</b>',
                  polyline: { points: 'komwFzfwbMICKCs@UOEm@SOIw@UGCYKGCyBo@sA[QEsAa@oAY_@EcBOq@M_AWC?GEWKGAGCIAGA]E_AIu@IkAQkAUIA' },
                  start_location: { lat: 40.7066222, lng: -74.01597749999999 },
                  travel_mode: 'DRIVING' } ]
            ,
            traffic_speed_entry: [],
            via_waypoint: [] } ],
        overview_polyline: { points: 'qoqaGn~tpLcKKN`PdW\\dQe]p^yHpWvm@|ZrM_DbbAJjlCwRjgBmh@liAnF`m@yJ~{AnEf|Elj@zeE|Yp{Elj@viBhCbrBlRr|BzGpsAp|@xzBt\\jj@nLhw@`]xgAhF~p@cJfjAcRfwCvg@piDzi@hxAhO|iCvn@xlAvj@znAv_AjuFfkAb~E|eA`hAb}AzrBfw@pnCiB|tBl@zqHfZfdCtExjEd_@dyBrk@duAvUrtArTldDfSnfB|h@prAxOzcBnr@roD`l@nxCdh@jaB|x@daC`Xfr@nIvfAbRjcCvt@`_Dv|@lxDb@|_@|Wrf@vbAn_Ali@fk@vsAx\\|lCpcB|{Fv_El`BfzBdeDrpBlkDj}BrvArfAdtCxkI|rBhgBzSpd@jn@jgA`tCfbIv`BpnEdO|`BiK|~@xH|wAPzxAtbBpyCfs@voBbl@vrDfy@nvAt_@zvAtc@peC|w@bz@f~AdcAvWfl@`C`y@~`@htDdb@npBhe@|tAxr@h_Ad|@f[bb@sFlq@saAxc@qNjuAoa@ff@}A|b@~P`z@h_@vaAv{@biBp~@tn@|Gh\\bWnpA`lAboB|y@t`Bl{@~`AtT`wAlcAzcApbBn}A|~@zaA`hBtXfV~q@jJnk@vb@dv@zcAh|@lqAfwA`rBn{CdjBlcDh{AndB`\\hrA`s@`mAl_Bbb@f}Afy@fvAhu@laAdC|i@j]~x@nd@npBbLbm@lbA|lAjnCntDxi@x}CzX`\\n`Bp\\fnAnbAhdDzxCbd@zgA|G|eBho@hhEe@hgBvd@bn@~[xc@tYvrAx\\vYnb@vRvXt^`i@zRle@dM~j@qKniA|Lt^cMj\\joAuHhjBbLvz@dYds@ljAvq@ro@nhDdIhx@jc@vo@bp@p{@p^j`BuDffEhQboDvv@vdC|YdnBpF~t@ba@pjAxu@|cAnTto@|`Atk@la@p{AtQh}@nA|p@rEhh@ra@vb@dYhWdMbo@dWrbAh^jwAbGlgBbU~sAff@rtBbl@`l@pv@twD`kAf`Bbx@lr@vq@lu@pJlbAvJbx@b`AhjBn@pjBvLd_@~a@pPvi@`oA|_Abk@npAlw@jw@hpApmAxsA~c@fU~Sf_@vrBpeApOvxBph@bhAv[|Enb@kLvv@k`@xd@kDnnBwFnf@xeAtMhkBb[lrEp}AhtBn_@``ArYz\\{Vhx@jLmGxYhCf{@p}@`TpXlZsGr[dIxR~TtjAteAf_BdqA~c@pNl_@gFv\\aJhm@bQvn@zVhF~s@r^~jBxSxa@h@b_@}ZvDcd@qKaDi@' },
        summary: 'I-90 W',
        warnings: [],
        waypoint_order: [] },

      { bounds:
        { northeast: { lat: 42.3674676, lng: -71.0517026 },
          southwest: { lat: 40.7015083, lng: -74.01588 } },
        copyrights: 'Map data ©2017 Google',
        legs:
          [ { distance: { text: '228 mi', value: 367103 },
            duration: { text: '3 hours 51 mins', value: 13863 },
            end_address: '285 Fulton St, New York, NY 10007, USA',
            end_location: { lat: 40.7129366, lng: -74.0139476 },
            start_address: 'Boston, MA 02113, USA',
            start_location: { lat: 42.36553, lng: -71.05528389999999 },
            steps:
              [ { distance: { text: '0.1 mi', value: 187 },
                duration: { text: '1 min', value: 67 },
                end_location: { lat: 42.3670453, lng: -71.0542919 },
                html_instructions: 'Head <b>northeast</b> on <b>Salem St</b> toward <b>N Bennet St</b>',
                polyline: { points: 'qoqaGn~tpLg@YOIIESKg@Wi@]ECIEs@a@k@]WO' },
                start_location: { lat: 42.36553, lng: -71.05528389999999 },
                travel_mode: 'DRIVING' },
                { distance: { text: '0.1 mi', value: 234 },
                  duration: { text: '1 min', value: 79 },
                  end_location: { lat: 42.36822, lng: -71.05664689999999 },
                  html_instructions: 'Turn <b>left</b> onto <b>Charter St</b>',
                  maneuver: 'turn-left',
                  polyline: { points: 'ayqaGhxtpLQj@Ob@KVWt@MZKXELe@dAAB{@pB_@x@' },
                  start_location: { lat: 42.3670453, lng: -71.0542919 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.1 mi', value: 171 },
                  duration: { text: '1 min', value: 61 },
                  end_location: { lat: 42.3672093, lng: -71.0582036 },
                  html_instructions: 'Turn <b>left</b> onto <b>Commercial Street</b>',
                  maneuver: 'turn-left',
                  polyline: { points: 'k`raG`gupLFLDJ`A`BDJFJNTLTPVRXBP@B@B@BJLJNDF' },
                  start_location: { lat: 42.36822, lng: -71.05664689999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.2 mi', value: 285 },
                  duration: { text: '2 mins', value: 101 },
                  end_location: { lat: 42.3647904, lng: -71.05838349999999 },
                  html_instructions: 'Turn <b>left</b> onto <b>N Washington St</b>',
                  maneuver: 'turn-left',
                  polyline: { points: 'azqaGvpupLZf@JPTVRKXKtBIpBI\\A^@H?fAA' },
                  start_location: { lat: 42.3672093, lng: -71.0582036 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '348 ft', value: 106 },
                  duration: { text: '1 min', value: 37 },
                  end_location: { lat: 42.36384839999999, lng: -71.058433 },
                  html_instructions: '<b>N Washington St</b> turns slightly <b>right</b> and becomes <b>New Chardon St</b>',
                  polyline: { points: '}jqaGzqupLFH@@@?L?p@@T@V?d@AZC' },
                  start_location: { lat: 42.3647904, lng: -71.05838349999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '315 ft', value: 96 },
                  duration: { text: '1 min', value: 17 },
                  end_location: { lat: 42.3632053, lng: -71.0577247 },
                  html_instructions: 'Turn <b>left</b> onto the <b>MA-1A N</b>/<b>Interstate 93 S</b> ramp to <b>Quincy</b>/<b>Logan Airport</b>',
                  polyline: { points: 'aeqaGdrupL^GBMBI@GFINOd@k@V_@' },
                  start_location: { lat: 42.36384839999999, lng: -71.058433 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.4 mi', value: 632 },
                  duration: { text: '1 min', value: 37 },
                  end_location: { lat: 42.3593851, lng: -71.0523058 },
                  html_instructions: 'Keep <b>right</b>, follow signs for <b>Interstate 93 S</b>/<b>Quincy</b> and merge onto <b>I-93 S</b>',
                  maneuver: 'keep-right',
                  polyline: { points: 'aaqaGvmupLTK@ABCHILOLMR[T]l@aAn@qA\\w@Ti@FO`@cAFQDON_@@A@EJWXs@Xq@@E?CDa@N]p@uAr@sAb@s@T[`@a@h@_@FEFCFCNGZIh@M' },
                  start_location: { lat: 42.3632053, lng: -71.0577247 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.2 mi', value: 388 },
                  duration: { text: '1 min', value: 19 },
                  end_location: { lat: 42.3559811, lng: -71.0514754 },
                  html_instructions: 'Keep <b>left</b> to stay on <b>I-93 S</b>',
                  maneuver: 'keep-left',
                  polyline: { points: 'eipaG|ktpLNEz@Q|@U~@QvA[fBi@`B_@JATERCRCVAN?L@N@NBNBLD' },
                  start_location: { lat: 42.3593851, lng: -71.0523058 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.8 mi', value: 1253 },
                  duration: { text: '1 min', value: 59 },
                  end_location: { lat: 42.347975, lng: -71.0608457 },
                  html_instructions: 'Take exit <b>20A-20B</b> for <b>Interstate 90 W</b>',
                  maneuver: 'ramp-right',
                  polyline: { points: '{soaGvftpLRHRJVJRHRLVPRRVZV^PVNVNZP\\Pb@p@zAt@nAfDpHPb@H^Lb@Hh@Hn@L|@Hj@Lv@H^BTBPDb@V|@Vp@Tf@P^Zd@p@r@XXf@RXPb@Nf@Pd@Jh@N^J^Fd@Fd@DZFhCl@PJJFNJNJx@h@j@^JFJFLJ' },
                  start_location: { lat: 42.3559811, lng: -71.0514754 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '3.2 mi', value: 5080 },
                  duration: { text: '4 mins', value: 236 },
                  end_location: { lat: 42.35531210000001, lng: -71.1185029 },
                  html_instructions: 'Keep <b>right</b>, follow signs for <b>Route 90 W</b>/<b>Mass Pike</b>/<b>Worcester</b> and merge onto <b>I-90 W</b><div style="font-size:0.9em">Partial toll road</div>',
                  maneuver: 'keep-right',
                  polyline: { points: '{anaGhavpLNHNJLHFDl@`@FDLJFFJHFHLNFHFLDJDLDVBH@HBF@D?B@H@HBJ@J?H@H?H?J?H?JAJ?LAPANARCVCPCVEv@EZEXG^EZEVGXE\\GXYpBGZEZEXE\\E\\CTC\\E^AZC\\C\\[fEC\\C`@AZCXA\\CXAZA`@AX?\\?ZA\\?nO@pB?xDL`R@xBF~JDbG@hA@hADhLDfLDrE@xC?ZAVC`AAZA^Er@Gz@IbAGdAAd@A\\Ad@?p@?r@?tA?rB@bE?|@?tF@lC?rD?tC?rCBfI?rA?z@Az@?f@C`@Af@EbAEr@E`@CZSnBq@|F_BrNa@tDWzBKr@WpAOv@c@hBa@nAUr@Uj@KX[p@Sb@m@pA}@nBo@rAEJKTKVKXKVELGNGTIVK\\K\\GVK^ITIZK\\IVIXKVKXMVKXMVKXuErKe@fAMXMVMROVMR]d@QPc@b@]VYRk@ZWJ{@d@' },
                  start_location: { lat: 42.347975, lng: -71.0608457 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '52.1 mi', value: 83793 },
                  duration: { text: '48 mins', value: 2855 },
                  end_location: { lat: 42.1324802, lng: -72.05108369999999 },
                  html_instructions: 'Keep <b>left</b> to stay on <b>I-90 W</b><div style="font-size:0.9em">Partial toll road</div>',
                  maneuver: 'keep-left',
                  polyline: { points: 'uooaGriaqL_Ab@iAl@_@VMHOLa@`@MLk@t@]h@KPUf@Sj@K^ELQt@ETCPGf@]`FANEd@ANCr@A`A?Z?|@?fABj@@^HzAHp@D\\BTLj@Hf@`@jBDPRt@Pt@ZrALv@FZFZD\\DXHz@D^Dp@Bj@BV@d@@l@@H?x@?t@An@Ab@A^AZCb@AXGx@Gv@ARMhBSpC]`Fk@bICf@OtB]`F?BCXOtBSzCInAK~AKlBKvAKxAQxCGz@Er@OrBUrDGt@E~@G|@AVAd@C|@An@Aj@?r@@x@?n@DvABn@FtAJvARtCLtBHpBBz@D|@?`@DvBBvB@z@@z@?x@@^@dA@dAFnFFvDBdD?v@?@@t@VvT?D?t@?@?DB~@HjIJ~J?H?fG?^?l@CbEAfAGfDCnBGvBEpCGzEGfFIlFKrG?z@?n@D~DFzAHxAH|@Hx@`@jD^jC?Bh@vDZbCZ`CBTF^?BLv@VzBX|BLbALfAd@zENzAFt@HfAFf@^fDLh@J~@\\lCp@dFf@zD^nCR|ALbAFZDZN~@Nx@RjAHf@\\`Bf@jCHd@d@zBZ`Bj@vCr@vDlAhGTjA`@rBH^DVLp@P~@Jh@Nx@ZpBZlBTdBRtAPxARzA\\zCB\\JfAVlCJpAZzDXnEBVb@hGVlDVxDHpATrCRzBPdBHn@R`BVjBn@pExAfK`@tCVfBh@nFBTPjCHfADbAF~@B|@@NFlAXdHFrANpDFlA@h@Bh@Dt@NtD@TDj@NlC?DFhADf@B\\H`ANpBJvAHx@Fx@Hz@Dz@Bv@B^Bt@@v@@t@@jA@|A?t@BhBBjAB~@DbA^bJHzBNpD?BDp@rAl[Br@JpBLtCDbAFp@Fn@Hz@Jv@Jj@RfAJl@Pn@Rr@Tn@Rl@Zv@Th@NXR^l@hA|@|Af@x@d@x@T`@Zj@Vl@NXN^Rh@HTJZBHL`@Lb@Rz@Hd@H^DTJp@\\nBlApHVzANr@T~@ZbATt@Xt@P`@JVHPHRNXR^Xb@xBtDv@xAh@jAJTHTPl@Jd@Pr@F^Lt@Nv@Jx@L|@P|AP|AD`AB~A?b@?b@?bACzBAp@GfFC`BG~JAv@Av@ClBAjA@z@?x@@|@@x@DtABz@DvADxADx@@b@CXh@pQVxILtDFvBFrAFvAFz@HvAHx@JtALtAPxAHv@PvABV`A|HZhCD\\n@bFt@pG~@nHd@vD^zC\\pCZbCXvCHv@PtBH`AJ`BJbBJpCFxBFjD@tC?`BAjBC|LAl@A|A?@?DAnC?HAz@?z@?\\?nB?L?x@BzA@t@DfBDlAD|@JdBLlBLdBLrABLNtALlAHj@PnAXhBZfBh@jCt@bDDRPl@^xAh@bB~@jCRj@fAbDNb@rDxKzClJrDvKjAhDlB|Ff@zAx@~B~@nCdA`Dv@vBnA|Cv@fBdAvBh@bAv@tAx@tAh@z@b@n@b@l@V`@`@h@f@p@`@l@Zb@nAfBh@t@`ApAt@bA~BbDvAnB`B~B|AxBlApBh@~@dApBZp@j@jAXp@\\x@l@bBN^h@~At@`CFVFTNj@l@dCVhARbALt@P`APbALz@f@bE^`En@bJ\\vEHpAPnBFh@LlAXxBZlBDRVtAXtAPt@\\pAZdANf@FTVr@b@nAZz@j@tA^v@b@|@f@bA^t@NVvApCjBlDd@dAf@hA\\z@`@jAXv@h@dBFVf@hBb@pBZ|ATtAXlBRbBZ|CN|BB\\F|AFpB?XBzA?jC?pAE~BGtAGlAI|AAROhBeA`Mi@jGe@tFOpBQrBW`DWvCy@vJOdBAPCRmA|NG~@E`@C^C\\C\\u@lISjCCXwAnPo@`Ik@pGUxBoBhQK~@MhAAJI|@QzA]vDQnBMnBOlDEdBCpBAtA?dC@~ABjBFbBFbBFpANdCL`B`@~DTdBXhB\\zBd@vCl@~DZpBF^@BHd@b@pCHf@Hh@PjAxBdNXnBtA|Ir@rEdA`Hb@`CfCnPf@zC|@~Fx@dFHj@j@hD~AhKnA~HZpBHh@@BHd@^|BH\\d@xBb@dBV`Ad@vAx@~BP`@Tl@n@xA\\t@j@dAl@lAt@xA`ArB@?nAdCfC~EtDrHNVvA`D@@p@`B`@hA^hA^hAl@vBn@dCVhAVhATfALz@BLb@lCLbALbANjAJjATbCJvAFfADbAHfClAxf@L`FJrDDpBLdFJnELtEDbAHfBF~@F|@Df@Fn@DXRhBNbA^|B\\nB^fBV`AZlATt@X~@\\~@x@xBBH\\v@Xp@Zp@pA|BzAbCrAfC~@~AXb@Xd@l@fARZtK|Q^n@RZBDDHHN^n@h@z@j@bAj@`Al@bAv@rAj@`AXd@Xb@f@z@f@|@p@hAt@nAl@dAh@|@j@`AvAbCzAhCv@pAx@tAl@bAj@bAh@|@h@bAp@hAb@|@h@hAd@bAZt@j@rAd@nA^`A~@pCf@`BBH`@zA`@zAh@zBh@hCTnAVvA`Pj{@~AvIbDdQpAzHJl@@B@JF\\RjA|BzNv@hF`Hvb@PjA?@N~@V`BPfAV|AXfB^~BrCnQRhAlBxLhAzGRvAVxA?@N~@hAdHdAzGTtARrAp@bEZpBj@lDj@jDJt@PbATvAbBjKPlAPfA\\pB^fC`@dCLr@^vBZpBj@nDhApHP`ADZ@Db@pCd@lCb@`CZzAZvAPp@FTn@zBFT^fA~@zC`BfFz@jCRl@^dAx@bCzBvGDJFRf@|Ah@~A@Bf@xA@BbGxQz@fCp@rBj@fBPd@?@DL?@@@|@pClBzFz@`C\\~@Xp@v@bBv@bBl@hA`AbBPX\\h@h@v@z@lAb@j@RXTVhArAf@h@v@v@~@|@vBpBbCzBnAhArAlAjAdATRPLpBhBv@r@bA~@~BrB`@`@dExDfB~AxApAhB`BbCxBlAhAhAbAhAbAh@d@vBlBzBpBnCdClCbCZX`BzAxHbHl@j@bAdAl@n@dAlAj@n@nA~AtAfBfA|AV^zA|BjB~CpErHzDpG`DnF`A`B|AjCfAhBnA`CPXh@dAfBxDnAzCn@~Ap@bBnFdNnBbF`@dA|@~BVl@^|@x@xB`@bAz@vBlAxCfArC|@|Bb@hAtBnFt@nBZ`Ad@xA`@xAr@`CNt@R|@Nn@Jl@Ll@t@jEjArHRrAL~@vCxQnA~HRvAJt@Jp@NvAJbALnAFx@JlANnCHjBDjBDlB?v@@t@?j@AhCAp@CrAAb@Cn@GlBGdACd@QjD[dGK|AOrCg@pJUpEUlEo@vLKlBOzCMvBUfEOvCw@bOQvCAd@QpCGxAEn@IrCEvB?dAAlB@vA@dBBhABx@DrABb@FvAHrAJvADh@LjAJ`ABZHp@PvAvBdPR`BVpBPrAHt@Jx@PnBNlBHpA@N@ZBj@Bh@Dx@@z@@h@B|A@bA@V?T?f@AxACjEYtTMpKMpLM~KIhFKxIShPEvEa@f^AfCBnDDvBNtD?@H~APtBF`AJ~@RlBPzARrAj@hD~@|Ed@fC~@xE^pBNt@bCnMBLf@rCh@nCH`@`@bC`@jCp@~En@fGXjDJxAXfFRnF@d@DnA@f@@t@@VFfJVpZRvVPdQD|E@`BDfEHdJBnDBxA@vADvFRlT?P?L@xBHtG?x@D`E@j@?h@DtCJhFBv@@d@FpBJrCLnC@LJlBFfAJrBRrCVjDb@dFPdBZ~Cd@fEPrAd@jDf@hDbAlGRnA\\dBBPVrA`A|EhAfFPt@XjA\\vAlBfHJ^`@tAf@fBb@rAh@bBh@~Ab@nAVv@t@tB|@`ChApCfAnC~@vBnAtC|@vB`A~Bn@vA~@zB`AxBhApCp@xAXp@jCjGrA|CjBlEhAjCdAfCVj@N`@@BLV?@?@JV@??BR`@?@FLbDvHRf@JT@@HR^z@Vn@Vt@Rh@n@nBh@bBZlAZlALn@f@~BDPBLf@xCL`Ad@lDb@vDFt@Fr@@NDl@FfAFdADxAFnCDbCLfHH`FFxCDtCFlDJ~FDjCHfEFtBLxDJvBLjCLvBPhCTtCLzANlBJ|@\\nDb@zDVtBjBnONpAL~@h@jEHx@f@dERfBP|A^~DRfCb@lGh@xIH~ATzDFnA@?Dx@`@tGZtFNbCNtCf@rIN~BNzBJxBJzADj@NlBTjBJx@LbAPhAJf@Nz@Nv@^bBZlARv@^lA^jAb@nAd@jAb@dAVl@\\p@v@zAh@bAj@`AvAfCbCjEb@v@f@`ALTn@tAr@zAp@dBP^BH^bAnA|CJXBJFPVn@HVlAhDJXp@lBTn@`@pAZ~@~A`FpAjE`AhDp@hCThAXlAVvA^jBZvBPtAZrCTtBLlBLrBHdBHvBBhADtALpEF~BVvIHpADv@JvAJzAFn@LrAJ|@TfBPtAVvARjANz@R`A\\zAH`@ZpA\\lAh@fBh@fBj@bBl@dBj@`B~@pC@Bt@dCp@pBj@dBRp@L^b@|Al@hCTdATnAjFdZhBbKz@zE`AlF|@bF\\rBLr@PtA\\tB`@dDf@hDnApJ|@tG~CnUBJ@LNjA`@`CN|@?Bp@~DFZ`AtElAtFrChKpHnW?@nAnETz@XdAb@lBZrAZnAH`@v@vDv@hE|@pF`@zCL|@PrAx@vGt@dGp@zFl@pENjAR`B^bCn@zDp@pDf@dCRz@Pz@R|@Nl@\\vA~@nDJ^Tz@Vz@HZZbA^nAn@nBTp@^fAJXVr@h@vATn@Xn@d@nAd@fA`BxDtAdDjAnCdB~D|BrFz@rBz@nBHRt@fBhBhEl@tAhAlCBFx@nBn@xAn@|Ap@|Aj@tAbAjCp@fBn@dBt@~B\\bAjAzDfAvDlAbEdAnDTv@`BrFh@jBzA`FnEjO?@nAdETv@Tp@Vt@~ArEh@tAp@bBjAvCrA|Cz@hB^|@nArC|AnDbAbCTj@`@jAd@vA\\bALb@`@vAj@vBNl@XlA`@lB^vBd@pC`@lCNhA\\zCJhAHz@JpARfDJ~BF`BXrPHxFPlLNjKL~FDnARfEBr@LfCLzBBPHhAHr@B\\^dELxATlBP`BTjB\\nC\\jCJz@PrAX`CPvA`@`D^bDDXb@jDL|@XfCZbCj@pENhAj@|Ed@tD\\lCl@|ExAxLz@zGVrBd@tDVhBh@hDLz@l@bDNx@n@dD^hBRx@t@|Cx@dDRr@Rp@r@hCj@hBx@fCtAzD\\|@vArDnB`FxDrJt@lBz@vBdAlCrBjFn@~AhAxCh@zAl@hBt@|Bh@dBTv@~A`GXjAr@vCt@jDLp@Nr@d@dCl@bDf@lCXtAZbBt@|Dl@xCx@jEj@fClCtLp@tCdDzN`GxWpAvFtAvGfAxE' },
                  start_location: { lat: 42.35531210000001, lng: -71.1185029 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.9 mi', value: 1489 },
                  duration: { text: '1 min', value: 64 },
                  end_location: { lat: 42.1267354, lng: -72.06602769999999 },
                  html_instructions: 'Take exit <b>9</b> for <b>I-84</b> toward <b>US-20</b>/<b>Hartford</b>/<b>New York City</b><div style="font-size:0.9em">Toll road</div>',
                  maneuver: 'ramp-right',
                  polyline: { points: '__d`GfnwvLRrAzB|JH\\H`@H\\FXF^FXD\\F\\BZD^BVB^@\\B\\@Z?^?TA^?^A`@AZCZAZQnCC\\CZC\\AZA`@AX?\\?X?\\?ZB`@@^BVBZB^D\\DVF\\F\\FZHXHXHZJXJZHRLVLVLTNTJRLPLPRZNRPPLNNPfH`I`AjAfCrCfCnCVZ' },
                  start_location: { lat: 42.1324802, lng: -72.05108369999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '42.1 mi', value: 67695 },
                  duration: { text: '36 mins', value: 2181 },
                  end_location: { lat: 41.7668105, lng: -72.6535956 },
                  html_instructions: 'Continue onto <b>I-84</b><div style="font-size:0.9em">Partial toll road</div><div style="font-size:0.9em">Entering Connecticut</div>',
                  polyline: { points: 'c{b`GtkzvLJJZ`@n@r@nE|EzAfB`IdJl@r@~A`Bn@n@^\\l@h@jA|@pA|@xBrAhCvAnAp@nBhAfAp@PJ^X\\X`@\\l@p@`@^Z^TTPVl@z@PTT`@JNNTXj@f@~@|@hB`CxEp@tAj@jAl@fAd@v@PTNVn@|@JLBFBBDFFHPTDBl@n@l@j@pAfAfAv@v@f@|Az@n@Xn@VpC~@`AVb@LLDf@P@?XH~@V\\LzIdCpGjBdDx@dCf@nHtAnCf@p@LnCf@rB`@h@JlB\\`ARTDVFVF^Hb@J^Jd@Lz@VpA^JDlBp@nBt@VJTJTJ^NZNf@Tf@Tf@Xh@Vv@b@|@f@lAt@f@ZXP\\TlA|@jA|@t@l@~ApA~BlB`ClB|BjBjDpCt@l@|CfCpCxBr@l@l@f@rAdA|@r@vAdAlAx@^ThAr@hAp@lAn@r@`@`Ab@pAn@rAh@|@\\rAf@|@ZhBn@pAd@~CfAJDNDz@Zr@ZfAb@j@VXNxAr@dAj@t@\\x@f@nDbCx@j@zAjAdAz@lAbAhAbAdA|@f@b@t@p@b@`@t@t@t@p@d@b@r@p@p@l@jAdAlBfBnBbBLLRNz@r@LJ~AjA`BhAdFlDx@h@x@l@f@\\b@Xt@d@j@`@B@?@l@`@XNd@Zf@\\t@j@PLz@n@x@j@fC`Bd@\\~BzAb@VVP^TVNd@X\\RxAz@nAx@d@X~ExCRJ|ClBx@h@XNh@\\h@ZZRVN^THFDBTNTNlAt@jAt@h@\\jAz@jAx@fAt@fAv@xAhAfBtAfCrBhA~@zAnAb@^v@p@x@l@d@\\v@l@f@\\pBtAd@Xh@\\tBlAz@f@`Bz@h@V`Af@dAd@rAj@lBv@jFnBx@Z`Br@pAn@vAt@p@\\`@TTLNHLHNHLJXPnAv@vAbATPz@l@fA|@dAz@xAnAXTfA|@~BpBnB`BzAnAv@p@~BpBhA~@hA`AlCzBnAdAd@^t@p@hA~@v@p@bAx@|AtAt@l@l@d@t@p@jA`AXTZXd@^LJf@b@b@\\RPTR^ZJHHHLJl@h@f@`@j@f@RNb@^rBdB~BpBfDpC`@ZrAhAl@h@f@b@NN\\^^d@TXX`@V^Vb@R\\h@dAXn@r@tAb@~@h@dAv@zAv@|An@hAHR\\l@^p@dErH~IdOzAbCdAhBjBzCl@bA^l@l@`ALT^n@jBxCP\\l@bAn@bAV\\NTT^PRPTp@x@b@d@^`@d@b@f@b@x@n@f@\\ZR\\Tz@j@|@j@x@h@|@j@bBfA|BxAlCdBnAx@z@j@lAt@~@n@fBhA~@l@bBfAzClBhBfAlC~A`Af@~@h@bB|@~BrArCzAnAr@h@Xl@Z~@f@rAp@hB|@tCrAtAn@`Af@~@b@tAp@lB|@~@b@tAp@rAn@lB~@`ChAtAr@tAr@z@f@rAt@dBfA|@j@pAz@|@n@`BjAx@l@zDtCdBnARNbBnAnA`ApA~@`@ZfBrA`Ap@`Ar@VRVR^V^V\\X^V`@X|@l@b@\\b@\\`@Z`@Z`@Z^Xd@ZnA|@\\VVRRNVPh@`@n@b@ZVv@j@^Xp@f@n@d@n@d@`@V`@VPLv@h@v@h@z@h@x@f@f@\\z@h@p@b@r@`@h@Xj@^d@X`Aj@p@^r@\\TNd@Vd@Vh@Xj@XZPTNVLZPZP|@b@z@d@bAf@`Ah@ZP\\PRJRJ`@Rh@Xh@Xf@XRHx@b@t@`@t@b@~@h@x@f@n@`@j@^r@f@PLd@ZjAz@jAx@h@`@h@^t@h@lAz@VPd@\\f@^RJz@n@RLb@Zd@Zp@d@p@d@dAv@l@`@r@f@pA|@dAt@p@f@r@f@r@f@r@h@~@n@ZT\\TZRv@j@b@\\b@Zf@\\f@\\RNd@Zd@\\xAbAdAr@dAt@XRXRXTZVRNx@h@v@j@b@Z`@XHFPLPLn@b@n@b@RP`@Xb@VPNRNRNlAx@f@\\f@^NJb@Zb@Zp@d@p@d@r@f@d@\\\\VTPh@^l@`@ZTVRf@\\f@\\lAz@XThAv@|@n@|AfA|AhApDdCvAbAxAbAf@^f@^v@j@f@ZPN\\TXR\\V\\VrA|@fAv@PNzAjAfA`ALLXVXVfAhA^`@b@d@x@~@Z`@JN`@b@NRRXRZRTPVNV\\h@^h@PZT`@Vb@V`@N\\^n@P\\PZP`@Xl@Vh@Vj@Tj@HPb@fATl@Nb@N`@L^Pd@Pd@\\jA\\jAX|@X~@v@hC`AnDn@|BbApDjBtGj@xBjAfEt@jCt@lC`AfDvB|Hh@lBj@lBv@lCr@pCtBnHbApDz@|Cl@|Bl@tBf@pBjAfEd@~A`@nAZ`A`AxCjBjFzAfErJpW`@bA`r@hkBxCnIxBxEfCtErAnBlAxA|C`DlB`Bp@h@pC~BhDhCl[zV|`@r[rArApB`BvDvCzC`C~ApArC~BtB|Bt@~@VZ`AvAjArBhAzB^z@j@zAl@hBL`@HRPn@@BPp@`@jBd@dC@HNx@b@zB^lBl@|CPx@\\`BV|@Pp@Ph@Rp@Xx@Tl@Vl@Vj@j@fAv@tA`@p@j@z@fAvAfAnA|@~@dDbDt@r@`A~@vAtA`C~BhBpBDDDDjBzBl@x@|@zAjAzB\\r@\\v@L^`@fAFLjAhD~BrG~@nC|@|B~C|IvBhGZ~@Pj@fBdFJZbBvEnC|HtG~Qd@pAz@`CN^N\\Pf@jF`Ov@xBN`@~AtErAvDjDzJdG|PbC|GfDlJn@fB`BxErElMhBhFrBzFpArDnAxDb@nAv@zBb@nAZ~@Vt@n@bB`@lAl@dBv@vBb@jAt@vBt@vBl@hBVr@Vp@|@dCf@tAb@nA\\bAfB`FzBnGv@zBv@xB~@nCjAhD\\~@b@hAd@rAl@bB`@nAb@hARl@^bAv@zBb@hAx@~Bv@|BfA|Cp@jBp@lBh@zAbAhCh@zApArDbArCBFHTTp@t@nBxAdEp@pBxHlTrFxOf@tAf@xAfA|Cf@tAj@~Al@`BJZTl@`@nAj@zAp@bBVj@HPN\\LXDJ\\t@n@nAlAzBjBlDfArBdAlBl@jAb@|@l@tAVr@N`@Tp@Rn@\\nAXnATfAPz@TrAd@zCZtBXlBf@dDXnBRrA^fCXpBZvBTbBp@rEt@fFl@dEr@`FPjAJx@P`BJbADt@Bl@BhABt@?n@?b@AdACv@Cz@Er@IfAGr@Gl@E\\Kp@QdAUhASz@e@dBu@hCiBnGSp@Sp@Md@Sz@I`@Kj@G`@O`AE`@E^Ef@Gp@El@Ej@Cv@At@C`B@bB@r@Bf@Bh@Dx@Fx@Dj@Jv@Hn@Jp@Jl@Jj@Pr@Pr@d@lBr@tCPv@Jj@BHLr@L|@Jt@NxAFx@B\\Dv@@j@B`A@pABhD@|B@pBDhGBnDBbF@rB@|B@pD?b@At@Ax@Cl@A^Ef@YbFgB`ZGhAG~@GlACbACh@Ar@AjA?lA@`A@nADlABh@Bh@HvAFbAJ~@Hv@RzAHh@Lv@BLHh@Lj@Jb@TbA`@~Ab@vARl@Xx@Xr@`@`ANZx@`Bb@t@Zh@l@|@\\f@`@l@lFhH`LnO~J`NnKrNRX^j@\\f@x@rAn@fAdApBn@pA\\v@j@nAp@|AjNj\\rA|CXl@bFpLbBzDxBnFpCtGzChHbB`E^|@rA`DdGnNfAlCpAzCf@lAfA~B?@Pb@Tj@Zr@Th@Rf@b@lA`@fA`@lAd@~Ad@bBXjAXjAZpARbARdAR`ALv@Hh@\\rBRpAr@pEHh@@HF^x@~E|@|FbAvGv@bFpAlItAtIz@lFrApIj@fDrAnIXhBtBtMzAxJHd@BPxBdNlAvHd@zCJn@\\rBTvAXjBRrARnANz@XrAPt@H\\Rv@ZhANf@Nb@J\\Xt@P`@FPNZR`@jCtE~@zAdAxAnBnCnP~Ux@jAf@r@vArBb@n@j@v@\\h@x@lAp@fAl@bAj@dA^r@d@|@f@dAZr@f@jAZv@d@hAf@tAn@nBRr@`@rA`@zA\\pAVfAPz@pAdHPjA@FVfAJd@R~@Nr@h@vCNn@XtA^~A^tAb@~ANj@^hA\\dAv@xBf@vAh@lBl@dBt@|B~@hCFPr@nB|@jC~ArEbDhJX|@Rn@BHn@zB`CpJbA`Fn@~Cf@pCd@tC|@bGd@`EZtCVnCJtALtATfC\\bDFn@Jv@Dh@nAhNVlCFj@Fh@Hj@Jp@Fb@Ln@H`@Jd@FVBHFXDN\\jAH\\N`@f@rAPb@Rb@f@dA^p@b@t@Zh@d@p@fApA|@~@ZXn@h@VP^ZxAfAbAr@nGtE`D`CjAz@FDdBpAxDpCtF`EVRxAjAhEnCjTfNt@d@jAx@bAf@|Az@HFxJhGvBnAdAr@xA~@nAv@n@^j@\\rAz@XPtCfBx@h@|@h@hAp@p@b@n@`@p@b@v@d@l@^TP\\Tp@f@x@p@r@n@TTXVn@p@TV^b@f@n@RVV^v@jA^j@`@r@Xd@R`@`@t@Tf@Xn@|@|BN\\Vv@Ph@Ld@Rt@V|@Tz@?@HZJZJ`@Ld@XlATjAJp@BJ?@N`ABLF\\Ff@Fd@Fb@Ht@Dl@B`@Db@Bj@Bn@Bn@Bb@DzA?hA?~@AhCAhCAvB?v@ArB@x@@z@@x@BdABz@Dv@Dt@Fz@XzDHpALdBZrDPfC@FLdBPrBh@dIlAvPb@~FRfC`@`FPrCLzABT?@t@dK\\|DZ|CPvA\\jCfAfH~@~FxAjJv@zEn@~Dx@vDbDxRF^ZnBd@vC~CvQzBbMdAzFvBpNxC~Qd@~CLx@Jz@PxAJx@RpBHx@LrAFt@JvAHtAFvAB\\Br@BdABlB@xA?tCAhBAv@Ax@Cv@Ex@Ct@Ev@Gt@Gx@Gv@It@Kv@Kr@OfAkAvGi@zCKj@UjAG\\CLIh@ADER?@SbAMn@Mr@Ot@Ov@SpAObAO`AMt@ETqB|KADCJCNKj@a@zBk@vCI^ETIb@' },
                  start_location: { lat: 42.1267354, lng: -72.06602769999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '2.1 mi', value: 3438 },
                  duration: { text: '2 mins', value: 145 },
                  end_location: { lat: 41.7653147, lng: -72.6907251 },
                  html_instructions: 'Keep <b>right</b> to stay on <b>I-84</b>',
                  maneuver: 'keep-right',
                  polyline: { points: 'qq|}F~cmzLc@nBc@jBCJU~@i@~BUbAc@hBYnAADYjAQv@GXSv@GZI\\i@nB}@nDKb@?BCHA@On@K\\Ot@Qx@Kt@G`@M|@Eh@Ev@Cr@?|CBdSAj@?n@?V?XBlB?bB?jB?`@A@CzAQjFAf@?@Ch@CbBEtCCx@ClB?VEnCCzAAb@A^AVC^Gd@Kz@CPEVERIZGTIZYx@Wr@c@lAEJ]z@Ur@IXGZKf@E\\E\\CJC\\Eh@ATAZ?L?V?d@@d@Bf@Dn@D^Jr@Jd@R|@L\\Rj@JVPXR\\LR`@h@h@h@`@Zb@XhBdAdAl@p@`@b@XXT\\Z\\^\\`@v@lAp@pALZPd@JZHZRt@ZlAz@dD^dB`@bBh@fCvBzJ' },
                  start_location: { lat: 41.7668105, lng: -72.6535956 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '64.0 mi', value: 102962 },
                  duration: { text: '1 hour 0 mins', value: 3617 },
                  end_location: { lat: 41.3888688, lng: -73.5942743 },
                  html_instructions: 'Keep <b>left</b> to stay on <b>I-84</b><div style="font-size:0.9em">Entering New York</div>',
                  maneuver: 'keep-left',
                  polyline: { points: 'eh|}F`ltzLb@tB\\xAXjAZjARp@Rt@Tp@Tt@Xv@Xv@HVRd@Tl@n@tAZj@Xh@PVLRn@|@VZVZZ`@\\f@PTLTLRJTFPJRJZj@dBHZL`@`@lAJVHNLZXh@HNT^PVTTPTTPPPNLLHRLVLh@Xt@Xb@LTFPB~@L\\DTB`@Dj@@j@Bf@@T@h@@x@@hE@zA?bA?V@R@P@nANl@J`ATb@Nr@V\\L^Pz@`@d@Xf@^`@\\j@l@Z\\LNlA`BTXj@z@NZT\\R^P`@Xp@N^Rh@b@nAPp@Jd@Pv@Jl@FZJx@Hr@D`@BXDl@Dr@@Z@j@@z@?nAAfBCfBG|FCxA?BCzAElDChCEpI?p@GpVAhBAxFA`C?ZIh\\A~G@hA@p@Bn@@^Dr@B\\@FHv@NdARxAPdAdAlGt@`EZrANf@Zz@?BBD?@Zl@^l@`@j@RTb@b@TN@@VPl@Z^L^Lb@LVFn@FP@X@|@CfAEfDQpAEjBI`AE`@Al@Aj@@|@Hx@Pb@Hj@Rn@VZNTNt@h@`@\\RPpBlBLJdEbEdD`D@@bB~AvBtBJJrBnBf@h@PRj@x@`@p@P^P`@Vn@Rl@Rr@Nt@FZFZ?@RxAZfC\\pCVpB^tCZhCR~AX~B|@fHVlBFb@Lp@Jj@Pp@\\rATn@Tp@b@bAf@dAZh@X`@DHRV`@j@r@z@l@j@PNvAfAnBrAlAx@bBnAr@f@~@r@l@f@\\VTPVXr@x@PXh@x@`@t@`@|@FLLZBDTt@Vx@VdATfARxAFj@Hz@Bp@Bn@Bp@?h@A|AEvEO|LC~@?@A`AEzBE`EAtDAvC@tA@dCBnB@tADxBBdAFpBDfBB~@FzALjCLdCZ~Ed@dGZ`DT~Bf@~EH~@Z`CZ`CXdBp@dEr@`EJd@Nt@`@nBpAhGjAnFbArElAfGhA~E\\rAXbATr@d@jADLJRVj@^r@^l@LVp@|@v@|@rAtA@?j@h@d@`@d@^p@h@d@\\r@d@b@XhB`AlAj@l@TBBtB~@NDpCjAvF~BhDvAvAl@dBv@xKpE~KvEpIpD~BdAz@^rAj@`KhEnCpAf@VtCzA|ChBtA~@lAv@nChBVNn@b@fDxBhEpC`DtBtFpDjCfBpExC|FxDv@f@lAv@vBvAdC~Ab@ZfBjAr@d@dDvB~@l@z@j@FDJFpAt@n@^bAf@f@TJFNFPF`@P|@ZfBf@rBj@jErAxBl@|C~@hBd@j@P|@XvBn@zH|BrF~AjEnAnEtA~C|@rGnBjKzCz@\\~@b@fAj@DDd@Xx@l@`@^jA`AXZRTh@p@@@v@bAXb@HLLRHPd@dAJVN`@Nb@DJH\\J`@Nv@F^Jn@Fj@Fp@BZ@ZB\\?R@p@@l@Aj@?n@?h@Cn@Cl@A\\Ej@Iz@SnC]vD}@|JGf@]bEW`DOvB[lDUvCCVI~AGpAKlBAf@Cd@An@Ah@A~B?hB@`A@z@@\\Bh@B^BXB\\BZHh@DXBLJj@HXLf@HRFRPd@Pb@P^JTNTZd@JNLPNRRTXXJJNLt@f@PLZNt@\\hBn@|CfAf@RfA\\pDnAh@TpBv@nBt@bBp@bBn@p@ZhBt@~@b@b@TrAp@p@^v@`@|@f@l@\\nBfAZPdBlA~B|ArXxSfCnBxEpDvCxBrG`FtCzBrB|AfClBtJpH~AlAxN|KpNvKlNpKjF`Et@l@bAz@hBdBfDnDtChDn@x@`B|BhD`Fz@rAd@p@PVFJBBDHtB|ChBnCdA|AbCpDnEvGRXhAhBZh@jApB~@dBx@zAZl@f@`ANZp@xAzA~CvBpE~@nBnAdCbArB~@nB~AfDp@rAbBlD^v@`AtB`@x@`@v@`@v@LRVb@HNNX\\h@n@fAh@z@Zf@^h@j@t@RZz@fAbApAX\\f@l@tBzBp@n@RPlAfAtAlAz@r@nCtBtCtBp@f@xB|A^VnEbDvHtFt@h@|AhAbAp@dCzAjAj@bBn@vAd@b@Nf@Lz@RXFb@HVF`@Dd@Fv@L`C\\dCVjBRvC\\nEf@zC\\pI~@~APvBTdBRnBRdANtD`@lBTr@H@?n@Hd@Fp@Fb@FlAJ\\Bx@Bf@@Z?r@?n@?X?XA`@An@C~@Gl@GfAMh@I\\I`@I`@K|@Ux@UZKNGfAc@z@_@t@_@t@_@n@_@j@_@d@[x@m@x@i@f@]fBsA`BmArByAdAo@f@WVK@A~@_@p@Sx@Sh@I|AUhAIf@A~@?h@@r@DN@TBf@F`AP`@J^H|@Zd@NfAf@B@~@h@vDnCpKvHfD`CpLnIjTlOpEbDvB|AhFrDx@l@rA|@\\XpA~@`Ar@^T`BjA~AhAtBzAtBxA`BjAr@f@l@b@TPbCbBx@l@ZTRLr@f@NLf@^PJx@l@d@\\PNv@p@b@`@`@d@PPNR^d@PRj@z@LRPV\\j@Zl@LXf@dAVn@Vn@Lb@ZbAdBhFJXBLr@rBv@~BZ`ADLTr@`@lATr@Tr@Vr@Tr@j@dBp@tBf@zAZbAT|@JZ`AtC^hA`@lAjB~Ft@zB`@jA^hAb@fALXVl@Xn@h@dAZj@Zj@LTZh@^j@\\f@^h@^f@^d@NRPPNRNPNR`@d@^d@^d@`@f@p@z@^b@`@f@p@r@`AnA`AjAt@|@l@v@pA~ArBdCbCvC`BpBrA~At@~@~BtC`AlAp@z@p@z@`AjArCfD`@b@^d@`@d@NPNR\\f@\\h@Zd@\\l@JTXj@Vn@Vn@^jATr@`@dBNr@H^Hj@PpAJdAJnAHtAFvABxAR`H?RBbABz@@Z@\\BbA@P@ZDx@Dz@BXHv@Jz@Jt@Nv@FZNp@ZjATr@Vr@b@bAf@dA^l@h@z@NRNR`@d@`@f@^d@NR`@d@n@v@PR^f@`@d@VZV\\`@l@d@v@Zl@Xj@Vn@Vn@Tn@L`@VbANn@H^Lt@PpAHv@HrAFfABlA@^?f@?f@Cr@Cv@Cj@Eh@Gv@OrAMt@G\\Ot@EPI^Sr@Sn@k@dBmAnD_@hAm@bBaAvC_@jAm@bBCH[`Ak@~AuBjGCJw@|BsAbEM^_@jAw@|Bk@dB_@hAUp@a@hAKZITIRw@zBcA`Dk@~AGRM\\Sn@Od@Od@Sr@Ot@GZGZMt@EZEXKv@Ix@CZCXC\\CZCv@Ez@?j@Aj@?`B@j@@`@Bn@Bf@Dp@Ft@LxAHn@XfBVlANp@Pp@XfA|@lDZpAx@|CT|@XfAZlAb@bB^zA\\pANp@Rp@t@vCPr@`@~Ad@dBj@zB`@`Bb@bBb@~Al@`Cj@zBh@vBZfAXlAb@bBZlANp@FRFVLr@F`@Jl@BVHx@Dr@Br@Bz@?n@Ct@Cv@Gx@En@G`@EZMx@On@Qr@Qj@Qh@a@dAa@dAi@tAWp@Sj@KXIVK\\Oj@Op@G\\EPGb@E\\Ef@EZEp@Ah@Ct@AnA?bB@|D?h@@t@B|@LbBJtAL`BDbAB`A@tACzAEbAKhBMjAMbA_@fBI^Ol@Ol@Sn@M^w@xBOZSb@i@vAc@jAa@dAUl@_@~@Yr@Yv@MXYv@O^Uj@MZWf@[j@Q\\]f@Y`@a@h@Y\\c@d@{@x@_@Zw@l@a@Xg@Xe@Xc@Rm@Xu@XWHQFUFi@NE@C@[Fm@NaAViBb@w@Pi@LWJm@Pi@Ti@Va@Te@Zc@Z]Xi@d@i@j@s@z@[b@QXi@|@a@v@Wl@k@zAY`ASp@Q|@Qv@Kr@EZEVIv@Iz@Ch@EdACdAAjA@|@@n@@\\Dz@Dt@@H@RHrATxDVrDB\\Bb@Bt@@h@?h@?d@Af@ARCZIdAGf@Gb@Ot@Ml@WtAIb@E\\G\\In@Gr@CZC\\A^Cp@ALCdA?bAFvH?Z@N?H?R@b@@`@@^NjIFhBHhFBxBBx@DdCDtA@l@?X@j@?P@p@Bx@?J@ZDpB@THnDD|BBbAHfBRlBLr@Hd@Np@d@fBNj@Lb@L^Tt@FVRn@Vx@ZhATv@Nh@Nf@Pl@Rr@b@vAPj@Nh@X|@J^Rt@Nn@H`@Lv@Jx@Hp@B`@B\\Dt@H~ALtCNnCDv@B`@Dv@J~@Hr@Lx@Hb@Lr@Np@@DRr@Pj@L^Vt@LXVl@NXLVf@|@NTPX\\h@Zd@`@j@NVNRl@~@^j@`@l@j@z@RXLTLP^l@X^p@dA^j@NTPT\\h@`@l@Xd@NTRXZf@b@p@JNLRp@bAJPLT\\j@NXXj@Zn@Zr@b@bAVr@Vr@Rn@JZJ`@Pr@Rr@JXH\\n@|BNh@FPRr@Pn@Tv@Pn@`@pATp@JZTn@JVLXJXLZFJ^x@\\r@HPLTLTNVPZNTXd@R^V`@RV^h@PV^b@NTPRPRPRPR\\^b@b@RPPNPNPPRNVRLJRNRPd@ZRNv@f@TLRLRJTJRJRHXNZLRHTHf@RRF`@LbAXjAXbB\\|@JVBnAJP@z@D`BDj@?zA?nB?rDBxCAtBBv@@\\@P@r@H`ANx@L\\Hb@JRHXHXJ@?\\NXLd@Zn@\\n@`@`@XVPb@\\b@^^\\PPNNNPNNNRNRPRJPNRNTLTLRLTLTLVLTJTLTJVJVJTJTHTJXHVHTHVRn@Rt@Nh@Nh@Nf@b@zA~@xC^nA^nA\\hAJZJ\\H\\HVHZRp@Tv@Tt@Pn@Rl@J^HVPl@Rt@Rn@Pr@HVFXFRHZLr@Pt@Ln@Lr@FZLl@FXDTDVJt@`@dCHn@Lz@BNHd@Lz@Lt@N~@\\zB`A~G^fCtArJl@fE?@n@hEHj@D^F\\F^Jv@Lv@Jv@Lv@Jv@Lx@Lz@Lv@Jx@Lz@L|@Jt@Lv@L|@RlAFZJr@Lr@Nt@Lv@Px@\\dBp@`Dj@jC`@nB`@nBj@pCDPH^BHFVNr@Np@`@pBXrAXrAXzAVnAXtAXpAZ~ALh@`@nBXrAXvALl@Jd@Px@Nr@H`@Lp@HZFZH`@Nr@H^Nt@Nv@Np@Px@Px@Pz@Lp@Pt@VrAF\\Pt@F\\FZH^Nr@Nv@Pv@P|@Np@H`@Nt@Nt@Nt@ZtA`@pBVhANp@BFVfAPl@Tv@FVHVHVHXHVHXJXHVJXHVHVLXJXHTLVRh@NZb@bAd@bARd@P\\\\p@Vh@Zp@Vh@LVLVZl@Xl@Xj@Zp@Xj@Zn@Zn@Xl@Xl@Zn@^v@N\\\\r@Xl@Zn@Zn@LVVj@Zl@NXVj@LVVf@Zp@Zl@Zn@^v@^x@t@zAt@|A`AnBf@dAr@zALVZn@Xl@LRXn@Xj@Zj@h@~@NXZj@Zf@NVZf@X`@RZ|@pA\\d@^f@^h@^f@\\d@n@|@n@|@PTj@x@d@r@x@jArAhBl@z@lA|AbApAX\\n@z@l@z@p@~@\\d@Zd@^j@Zl@Zh@Xf@h@hAXn@P`@Pb@\\x@Rf@Nb@Pf@\\fAVr@Rr@Pp@f@fBRr@\\rAhBxGBJl@vBf@`BHX\\jATt@n@`Cp@bCNj@T|@f@jBb@hB\\rAPp@bAxDj@zBT|@n@bCBLhAfEx@~C\\rAlAvEl@`CtBdI`AxDX|@Rv@bAvDbA|Dv@|Cx@|ChAjEr@lC~@vDn@`Cv@|C~@xDfApEnAnFbApE^bB`@nBlBhJpAzGhAjG`ArFj@`DZlBrAhI|@zFPhAZjBl@hDDXFZNp@`@lBTfAT|@Pp@J\\Pn@Tr@t@|Bj@~AXr@Tl@h@lA?@DHLVXl@^v@h@|@v@nAZd@NV\\h@f@r@~AvBfEjFtBbCXZbAlAf@h@pAlA|AtARPzAnAt@d@`Ap@lG`Eb@TpBdA`ExBXNhAt@v@h@x@r@TTVXj@n@bAxAf@t@Vb@Xj@`@~@x@`Bb@bA|@tBv@lB|@lBl@tAh@lA~@vB|@lBx@jBn@tAdA~Bd@hAx@jB|@pBZt@h@bAt@tAt@fAp@dAp@z@n@t@t@z@bA~@d@d@VTXVVTz@x@|@z@`A`AzA|At@`Az@jAZf@|@bBJT`@z@d@nAd@pA\\lAXjAjCrJl@zBf@lBXhAZlATz@XfAZhAd@xAb@pAb@lAb@fAh@nAl@tAb@z@n@dAd@r@h@n@p@r@p@j@t@f@@@lAp@v@d@z@`@~@\\fA^|@XfAZpAZ|@PhAPpAL`AJhAFtABtA?~ACr@A`AIrAMtASrAUtA[t@SHCrBs@VKvCmAz@a@f@UtAm@n@YhAe@t@]xAm@~@a@dA_@l@Oh@Mh@Ij@I`@C^Cb@AN?N?d@@|@Fr@Hz@Lv@TdBf@z@\\hB|@lAp@t@j@FD|@r@f@f@fCfCpBrBrBzB~@dAp@t@|@bAbBhBpAtAzAbB~AfBdCjCfAlAl@n@zA`B|@`A|@bA`A`AtAvApAvAfAhAdAhAjAjAbAdA|@z@|AvAxApAhDbDpBfBhFtEbBzAj@f@|ApAnBhBbAbAj@n@\\d@b@l@^p@`@p@Tf@Zr@BHPf@Rn@Vv@Ld@Pz@Jf@Jj@RpAJdAHfABT?JB^B`A@z@?jA?|@QtDUbDUlDq@jJWpDM`Ba@lGEf@KlAKxAG`AGv@Gh@Ef@UlDKrAOrBIrASnCGx@C\\CXEv@Gv@KxAKnAQpCOpBIrAC\\Gv@C^Gp@Gx@AX?BC\\CZC\\CXIx@EXEZQjAG\\I\\Mn@St@Ut@Sj@Wr@MVITMVKTMT[l@MV[j@KRUb@[l@Yj@[n@KTMXOVYl@g@bAKTUh@_@v@Yj@AB[n@[r@Yn@[n@ADWh@gA~Bc@~@MXCFgBvD}AfDYn@_BhDKVMVMXEHSb@uClGkDpHO^MVKTKVWl@MXUn@Wp@KVKXSl@Un@kBvFcAxCUn@_AtCw@~B_@fAa@hAIV_@hAa@jAc@rAQd@Wv@GPIXGTIXQr@GTS`AKh@Kr@Mv@CXGf@Gn@Er@C`@ABARA\\AXAZA^AX?x@AX?P?H@\\@h@?`@Bp@Dv@Dr@Fl@H~@DXDZJr@DZFXFXDVFZNn@Pr@Rp@Rr@Rr@HXTv@b@~ADHRr@Rt@h@fBRp@Pp@\\lALf@?@H\\Pz@DXLv@F^DVHv@Jv@BXDZBXB\\BZ@ZBZ@ZBV@d@Bh@@\\@\\?Z?X@Z?Z?Z?\\AZAZ?\\AXAX?DAXEpAEvAQxECh@GpBAXKjCAr@Cz@?ZAV?\\AnB@\\BpB@v@FfBD`AHtAFz@Fz@HrAFx@B\\Fx@JvAHtAFx@PnCB\\B^?@LjBNrBFz@HtALnBHrA@ZBXBv@Bz@@v@D~A?h@@z@@f@?l@?pAApC?tAAhDAvA?x@?x@?ZAv@?t@?N?l@Az@@X@nB@v@FrA@XBZ@\\BVDh@Dj@Fj@Ff@Hp@F^DXDZDVF^FVJh@Jd@Pr@Pp@HZHXn@xBNh@^tABDFVHXHVhBpGZfAz@vCNh@Pp@Pt@HXFZVnAHf@Hh@Fh@Ff@Fj@Dh@Fv@@ZBh@@j@@\\@v@?\\?Z?ZA\\?XAl@Ch@Cj@Ch@Eh@CXGj@EZGf@Ij@Ih@Id@Kf@Kd@Ol@K^Md@Md@_@jA}@xCg@bBm@pBM`@[pAQv@Ml@Ib@GVIh@Ih@Gr@Ip@Ed@Cn@Eb@AXExA?r@A^?^?Z@p@@`@?\\B\\Bt@@\\BZFv@Dz@JrA@\\LlBJtABf@Dj@LtBJrANbCPhCJpAF|@Dd@NrAHn@Fb@Jv@RnARjAPv@Nr@XjAPp@\\lA\\hAVn@?@Tr@rAnDdAnCfArCvDpJDLt@lBrAdDn@`B`@dAt@`CHX`@`BJj@@@Hf@`@zBPnABXD\\D^BTNpBFv@HtATjD\\tEDr@Dn@PfCHtAFj@J`APpAJt@ZlBXrARx@v@lCPf@L^Xx@jCnG\\x@Zv@jAlCz@rBt@dBh@lAPf@Rn@Pl@Rt@Np@P|@Hh@NhABNFf@?@H~@FdB@`A@`@AdACnAEp@Ev@C\\Q~AU~AUdAU~@Uv@Sj@_AtBkAtCqAzCkAlCaBbDoB|DYn@ILO^[t@Yv@Sh@Ql@Ql@Sx@Or@Kt@Kr@Iv@Gp@Eb@Ch@Cj@A`@Al@?`A@r@@^@j@HjADh@D^D^FZD^DVDXFVF\\HXXrA|CpM\\xAXfALp@P`ALv@Lv@r@xDp@~DnAhH`C|MF^H`@xBjM|@rFRtAf@`E^dDt@dHTbC^dD\\nDXnCZhCJv@Lv@Lt@V|ARfARdANl@@Hd@pBf@tBb@|Aj@hBb@nAb@pAb@nAb@fA^z@d@`AN\\DHTf@v@tA^l@h@|@h@z@^h@^h@fChDp@z@j@x@V\\TXr@x@dAbAzA~AbDbDh@j@h@h@l@n@pApAXZ`@b@h@n@x@jA\\f@^l@\\n@^p@DHXn@d@fAJVRf@Tr@Nd@Nd@DLDNNn@Lh@Nn@X|AHh@Hf@Hf@p@pETtAFf@@FJj@Hj@h@|Cb@pBb@fBPr@f@dBl@bBb@fAb@fAP`@^x@n@lAp@lA|AbCx@hAp@v@\\`@t@x@`@`@`@`@`@^RPfA|@d@\\x@f@XPt@ZPFf@RVFf@LVDPDj@F\\B`@Bn@@d@Ah@AHA^C~@M~@U~@YnCgAbBo@lBu@~Ao@fA[VKRIb@QXKPITGRETGTETERCTANAR?H?P?V?h@BRB\\Dr@NVHVHRJTJLHVLPLPNRNNNPPPPPRLRNRLRNTNVJRLZTj@JZHVHXHXRt@Pr@?@Pp@Rx@Pn@H\\Pv@V`A^xA^bBZpATfAHf@Jv@D\\BZFt@Dv@@t@?|@Ax@?VC`@C`@Ch@Gj@G\\Gh@Kb@I`@I^GXIVK^Sl@g@tAs@nBe@nAw@vBGRQl@Y|@_@xAWdAGZMh@SdAIb@ETKj@{@dGk@rDwAtJeB`Li@dDmBhL_@~BmBjLa@dCOx@E\\]`CS~A?@QxAGz@CVIfAEdAInCEdACpBGbCYbLG~BO~FG`CA^EfBErBGpBSjIKrDE`BE`BE~@Gt@Gj@K`AO`AKn@Kl@Or@I`@Oj@Of@Of@Mb@Sn@Sp@Qf@Sh@Ur@Qb@M`@W~@e@tB?BUnAUlA?BQnAK|@MfAGz@Gl@Et@Cv@EjAA|@Ap@?rABzAB`BDj@Bn@Fv@Fr@H|@Hn@Dd@Jr@Hj@Ln@Px@TbAZrAV~@X`Ah@bBZ|@ZbA\\fAt@~B^lA\\fAb@pATp@Rp@Rp@L`@Nl@Pp@Lf@P~@Hb@Fd@Fj@x@dH`@pDL~@Jx@PpALv@RnAPhAPbANx@Px@Jh@Px@Nr@P|@T~@ZpAp@rCzAdGrAlF`@fB`@dBZvAXvAVvARnAPhARtALhAJz@Hv@JbAJ`AFn@Dr@H`AF~@Bd@Bf@Dp@BbAJpBDjADhARtFd@lLd@pMZ~GFrAJlCJrCZdId@rL`@lKb@nKFvBFlBBzCAhBArAE~ACn@GbBG|@IrAKhAQ~AM`A?BMv@In@O|@UnAMp@[rAYhAe@bBi@bBmDvJcCtGuCdImBfFSh@kDfJ]~@' },
                  start_location: { lat: 41.7653147, lng: -72.6907251 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.1 mi', value: 221 },
                  duration: { text: '1 min', value: 11 },
                  end_location: { lat: 41.3906019, lng: -73.5953092 },
                  html_instructions: 'Take exit <b>20</b> for <b>I-684</b> toward <b>NY-22</b>/<b>White Plains</b>/<b>Pawling</b>',
                  maneuver: 'ramp-right',
                  polyline: { points: 'mwr{Fd{d`MMFA@MZKTMRKNMNOLQLOJULYHo@JE?oBR' },
                  start_location: { lat: 41.3888688, lng: -73.5942743 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '29.1 mi', value: 46899 },
                  duration: { text: '26 mins', value: 1551 },
                  end_location: { lat: 41.0152829, lng: -73.71670739999999 },
                  html_instructions: 'Keep <b>left</b> at the fork, follow signs for <b>Interstate 684</b>/<b>White Plains</b>/<b>New York City</b> and merge onto <b>I-684 S</b><div style="font-size:0.9em">Passing through Connecticut</div><div style="font-size:0.9em">Entering New York</div>',
                  maneuver: 'fork-left',
                  polyline: { points: 'gbs{Ftae`MUHWH_@J]PMF]TSNQP]\\]d@QZSZMXEHKVENIXIXG\\?@ERG`@Gd@AZC`@?^Aj@@`@@^Bd@Dj@Hl@FV?BJb@HT@FN^JZP\\R`@Zb@RTb@b@VRb@VXNVJf@Nb@Hf@DR@T?f@Ah@Ax@Sh@Ud@Ud@[f@[z@g@x@i@d@[RKb@QTGREVAP?F?T@f@HVIhBr@dBp@tAb@x@VtCr@`ARvFz@rFt@~B^fB`@|A`@lAd@|BhA`Ap@l@b@`@Zx@r@j@h@hApA`ApAr@bA`A`Bv@`BHNh@rARh@JXL`@j@hBp@xBl@nBpC`JfEbNj@hBl@lBZhAZ|@xAxEf@|Ab@tAj@hBl@jBZdAp@zB`@pAd@~Ah@zAVv@t@nBv@nBZt@f@fAb@~@d@`A|@jB`AfBn@fA~AjCpAvBtBhDfCfEtBjDd@t@b@t@LTpAtBrBfD\\j@dAdBvA~BvA`Cz@tAb@p@n@~@l@`A|@rAr@bAf@r@Z`@b@n@l@v@lAzAf@n@nAzAp@x@p@z@l@r@nA~AjAvAn@x@p@v@zAjBp@~@hB|B\\b@l@t@Z^LPh@p@\\^`CxCfDdEf@j@~HxJtL`Op@z@tBjClDjEtAbBf@l@`BrBhB|B`GlH|@fARTj@n@n@p@j@f@dAx@~@r@ZRjAp@rClAh@RXHx@Tf@L\\HjBVrBTzAPfAJbANtANxAPj@HtB\\hAXvA^pBt@fGbClBt@bA^NFp@RHBD@B?LDr@PhARt@Hv@FpAHp@@x@@hAE`AIrAOvAUrA]lBg@v@Wp@QRGp@O`AUj@MPEf@I~@MdAG`@Al@CnA@z@FvAJlARd@Lt@T`@NnAb@nAp@n@`@ZTb@Zl@h@r@p@`@`@p@x@`@l@xArBv@hAdA~Ax@rAzArB`BrB~ApB`AdAvA|A|AzA~AbB`BbBfAhAfBhBlBlB`BdBpBrB|B~B`CbC~@`AvAxAvA|AtAvAp@n@t@t@r@r@tAjAj@b@jAv@r@b@hAh@l@VpBp@n@P\\Hl@Ll@J`ALv@Dt@FxBNfAHtALJ@rCN~APx@JbBX|@P`AXr@TtAh@hBv@hAd@hAd@jAd@NFVHn@Rr@Rf@Lb@H^HTB\\DZDZDH@J@N@Z@|@Fp@BdABv@BxAB~DJtGNbFJr@BlDLX?^Bn@DdAFt@JjANb@F|@Pj@J|@PbBb@bCp@v@RTFn@R`@LTJ\\NTHPJx@d@jAp@~@f@p@^t@^XLb@RVJ\\LNF^LfAZjCr@rA\\bCp@rFvAjCp@pCr@fBb@pBh@z@Vf@Nr@TtBr@f@T`@RxAn@v@`@zAt@~Az@|@b@`Ad@pAp@hAf@`C~@RHj@RdAXlAZ~@Pj@Jf@H`@Dr@DXBh@@j@Az@Cf@Cn@KbAOnBa@t@MfB]bAWl@O`A[z@[TKj@UpAm@jAs@PK^Uf@_@d@_@t@i@RQ\\]nAkA\\_@bCqC`BkBrA_Br@w@~@cAVYNQ@?f@e@XUZUf@[RORKTMd@Uj@U|Am@fAc@`Bm@vB{@pAi@x@[dBo@tAi@`A_@r@[j@YpAu@LIJGNIx@o@x@q@RO~AkAdDgCnEkD|@q@t@i@x@c@b@Uj@WjAc@ZIf@OZIf@Gx@Mv@Gx@CfA@h@@VBVBj@Fp@HRD~Bb@ZJRHRHZNp@Zp@ZlAh@hHxChBv@~Al@fA^tBp@t@Vp@R`AVtBh@pDv@xBh@fBb@bAVpAb@nAd@~At@d@Tj@XhCtAn@\\tAr@lBhA~MxHf@XnBjAxC`BdBbAlAv@\\PRJpAl@t@^z@b@t@\\rBv@hAb@x@Z`C|@jBl@lCx@n@P`Dv@bATbARnB`@~@PdAPpARx@Jl@H|@JvANx@Fv@HtEXbAFz@Dn@Bj@@z@DrBBtA?pBA~@AjBCzAEbAEjAGfAGbCOzBUhCYdEc@`BQhAM@?pAOlAMjBOfAKjBK~BKz@Az@C|@AvAAxA?`CBjBFhABxAHbBLjAHv@H`BNzARjANd@H|HlAnIpA|ATD?XFhBZdLdBtB\\j@H~ATxAVvARzARbAHh@Bd@Bl@@|@?bAA`AE^C\\Ev@In@IfASdB_@zAa@h@MlEgAnD}@fD{@|Bk@nBg@j@MNErA]hBe@`AWz@QdAQz@M~@Ir@E|@EbAAx@@bAB\\BlAHl@Fd@Fp@Ll@JpAZ~Bj@fAVhDz@|A^zA^bCl@~A^rA\\|Bj@tG~A`B`@fBb@rBf@vA\\jAVbB\\|@Lh@HjBX`@DlBRlBLlAHnADx@Bz@Br@@R?T?~@?hG?X?l@?rADn@@jAFbBJ|@Hj@FrANp@JlBZbAPh@L`@HnBb@t@Rt@Rh@PrBr@zAj@xAl@j@TdAh@v@^h@X|D|Bd@X|M~HhAp@t@b@t@b@dCxAf@XnAt@f@ZlAp@hC|Af@Zx@d@lAr@z@f@f@Zd@Vd@Zz@d@f@Zx@f@nAr@pAv@\\RrAv@z@h@bEbCrBlAhC|AtBlAnAr@vBjAd@TRJTJr@\\bAb@rAh@p@V~Ah@xAd@bBb@~Bj@tCl@L@vDh@rANlBPlBLL@~@FT@\\@l@@f@@dA@xB?X?hCAlB?`A?bA?fA?nABp@@`AF^B@?\\BpALtALvAR`ANfAPNBRD~@RtA^|@V|@Zj@Pj@TrD~Ap@ZHDRJf@Vf@Xf@Vf@Vf@VFBnQhJzAt@jB`AfCpAhB~@z@b@z@d@z@b@h@VnAp@|@b@nAn@vBfA|@f@bBz@nAn@dB|@r@^vAr@pAn@|@b@pAj@dBv@pChA~@^pAf@fDjApAd@`AZhDdA|@VbItB~Bf@xBb@tAXhBZ`En@~@N`Ef@xANpALdEXz@D~@DjADnABl@@x@@dB@nA?tAAfBCnBEvAEbFURAvBIdBIbCMn@C~@En@EjAEfAEh@?`@?bCDt@D`AHzAL~BTnALlDZL@D@B?XB~@J`AJ|@H~@Hj@FT@l@Fl@B~@Fj@@h@BT@j@@jABnA@`@?bB?fBAbECb@A|@?t@?bCC~@?nAAjBAt@Bl@Bf@B~@Hx@Jn@JdAR|@Tb@LxAf@t@Z`Ab@x@d@l@\\~@p@r@h@\\XPNb@`@r@t@`@b@b@f@h@p@l@x@d@l@bDlExAlB|AtB`ApAjAzAZb@d@l@`@d@XZx@|@v@v@f@^n@j@v@j@d@Zx@f@`Aj@~@`@lBx@l@RbBd@tAZ`ALxAPVDr@F`AFhBBv@A~@Az@El@Ez@Iz@OfAQbASVG|HcBrHcBl@KzHeB~EeA~A]h@M~A]pBc@xBg@bCg@rIkBPEdNyCdAShAWhBa@fGqAj@Mh@Mh@Kh@Kj@Ih@Ij@Ej@Eh@Cj@Ch@Cj@?h@@l@@l@Bf@Bj@Df@Dj@H~@Fj@Jh@Lf@Nh@Ph@Ph@Ph@Rf@Nh@Rh@Nh@Rf@Pf@NZJd@HTDTDTDRBVBR@VBT@R?R@T?T?V?TAT?TCRATCRCVETEVERETGTGRGTGRGRITIRKRIRKRKRMRKRMPMROPMPORONORSPQNQPSNQNSNSNUPULSLULWLSLUJWLWLWJWJYJYVo@Vs@dB{EVq@Xs@Xw@Xu@Vm@Rg@LWJWLULULSLUNSLSPSNSNQPQNOPQPOROPORMPMPKTMPIRIRITIPIRGTGTGRETETERAVCTCVAR?R?PAN@T?R@T@TBTBTBTDRDTFTFb@Nt@TbDdAn@Rl@Rf@Ph@Nx@`@' },
                  start_location: { lat: 41.3906019, lng: -73.5953092 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '7.7 mi', value: 12438 },
                  duration: { text: '8 mins', value: 484 },
                  end_location: { lat: 40.9382591, lng: -73.8066233 },
                  html_instructions: 'Merge onto <b>Hutchinson River Pkwy S</b>',
                  maneuver: 'merge',
                  polyline: { points: 'oxiyFlx|`M`Cr@t@\\~GtB~@TlHzBh@Nh@Pj@Pf@Lh@Nj@Lh@Lj@LvEdAhFhAjDt@h@Lh@Nj@Ph@Rh@Tf@Tf@Tf@Vh@Zd@Zd@Xd@\\d@^b@\\d@b@b@`@^^b@d@hAlAJNHHPTlAfBdFxHPVdAvARTV\\r@x@`@f@FHJJlAtAb@d@`@`@`A~@TVf@b@\\\\|ApAZXxAjA^Vf@\\|AhALHxAbAbB~Av@z@j@n@r@z@bArAl@x@f@p@nB`Cz@|@\\Xp@n@bAz@lA~@nBjAxA|@xD|B|@j@fCxAr@b@`An@bCfBfAbAr@p@t@x@v@~@jAzAfA~Af@|@b@x@`AtBx@xBt@~Bb@hB`@hBPjAj@dDBLBTTrARbATz@Z`Ab@bAXh@n@bAX\\f@j@\\ZZVXRlAv@vA|@`CxAzClB~@l@`@Th@`@XTZXXXl@t@\\d@Xf@`@x@Pb@Tp@X~@Pv@Hf@Hf@D`@Fp@Dl@@`@@|@@d@AXAnAIpCANG|BAbC?lA@t@@ZBpAFxAFv@NhB@H?@TdCV`Cj@hD^lBVdA|@|Cb@pA^z@LTVj@Vb@r@dAf@l@XZd@d@f@b@b@\\nDrBxA`Af@^l@b@\\Zl@j@RT^`@r@|@LPh@x@Vb@HRTd@N\\Th@X|@Ld@Nl@Jb@RbAD\\Hn@Fn@Fh@ZzDLlAHp@NjAr@xEX`CFh@VlCZhE@XDf@Bd@BVDt@Hp@Jp@D^Lr@ThA@FT~@Pp@p@zBTp@b@lAr@bBf@fAd@z@`@r@x@lARXn@v@d@n@`@b@d@f@fAbAvAnAlB`Bv@t@`@`@l@r@v@bAV^Xb@Xb@Zj@d@z@b@~@JTb@bAb@jAVt@f@|ADVTv@XhAh@`CXxAVzAPfARhATxAJt@dAtENj@b@`Bn@vBh@`BVt@Pd@DLRj@\\~@Vj@LXLTXf@Xf@X^Z`@PRZZd@d@VRl@`@ZTp@Zf@V|@\\dA`@jBr@tBv@NHHDHD^Ld@L\\DXBXBL@V@^?\\?NAPCVC^Ib@KRGPI`@Ql@[`@UfAk@ZQZOLEh@STGXIJAjAOTAX?b@@h@Fl@J|@T~Bj@b@LlB^`AN`ANtBXjAN`@Fh@Lh@LPH`@NXNn@\\PL\\VLJZXVVJLLNRVTZNTNVR^NZJVVn@@B?@?@Pf@J\\?@@BFPl@rB\\jAL^Pd@N^d@~@NXNRNTLNNRLLNNPNZV^XRJ^RTH\\NhA^bBh@zBp@jBp@hAd@j@TnCxA' },
                  start_location: { lat: 41.0152829, lng: -73.71670739999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '5.9 mi', value: 9448 },
                  duration: { text: '7 mins', value: 391 },
                  end_location: { lat: 40.8606726, lng: -73.8286308 },
                  html_instructions: 'Keep <b>right</b> at the fork to stay on <b>Hutchinson River Pkwy S</b>, follow signs for <b>Hutchinson Pkwy</b>/<b>Whitestone Bridge</b>',
                  maneuver: 'fork-right',
                  polyline: { points: 'cwzxFjjnaMpChBbBfAh@Zb@TXNj@PXFf@HN@T?T?b@?HAXCn@KVIZO\\QNKPMDCHITOFIDENQLQLQHMHMN[JUHSJYH[H[TgAH]F[Pw@Po@Vs@Vm@Xg@`@o@\\c@^e@l@k@n@i@b@Y^QXK\\O^I`@IVCTAZAR?R?j@FbAV\\Nj@Zh@f@z@z@v@x@n@n@\\\\ZV^XPNd@ZTLd@V`Ah@\\RDBNHJF\\NNJXRPPTTp@v@h@~@HPRb@\\v@FN^v@R`@JRf@r@l@v@ZXv@d@^PRHp@P|B\\~@Vh@PPF|@f@TLpAr@?@@?~Az@rAt@dBt@JBl@VVNdA`@bC|@pA`@r@Pr@PvCh@j@FbBX@@H@HB~@NZDfBZtA^lHlB`Bl@t@X`Bh@fA^b@LPFPDFBr@Tl@Lh@LJ@NBVBl@B\\?n@ERA@AVCd@Od@O`@O\\In@UDABAFAb@OREHCf@Ip@Gl@Cr@AjADt@Dt@JX@PDJ@TBXFj@JPDTDH@LDh@LrA\\fAZnA`@p@^dBt@l@V^RDBXNH@JD\\L`@NVHXHZHVFTDz@NXBXBjADfABRAVDF?p@?b@@n@DH@lBPH@JBZFB@HBb@Jj@NHD|@Xj@PhA^|@Vd@Lt@Pt@NRBVF^DR@X@L?@?F?`@@b@An@Gb@En@Mn@Mj@ORGVIRIpAg@`@Mr@Qt@OZGh@K@?\\G\\GlHmArAQfAMTAPAHAF?|CK`@AfA?nAB|@DZFN@VB^BdANx@JzCf@fB\\tCp@bGvAvBj@dFlA`Cj@zBj@bBb@~HlB`APp@J`@Dj@D`@BjABfA?fCBhEHpBFxBPrBT`@H\\D`@Hl@Pn@VpAl@tA~@l@b@NLNNfGxGHHTRXXdBdBjJbJlBdBvCjC~HvGn@b@dA|@nFbEBB@?p@f@v@l@' },
                  start_location: { lat: 40.9382591, lng: -73.8066233 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '72 ft', value: 22 },
                  duration: { text: '1 min', value: 2 },
                  end_location: { lat: 40.8605466, lng: -73.8288267 },
                  html_instructions: 'Take exit <b>4S</b> for <b>Interstate 95 S</b> toward <b>G Wash Br</b>',
                  maneuver: 'ramp-right',
                  polyline: { points: 'erkxF|sraMVf@' },
                  start_location: { lat: 40.8606726, lng: -73.8286308 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '2.0 mi', value: 3161 },
                  duration: { text: '3 mins', value: 152 },
                  end_location: { lat: 40.8370699, lng: -73.8252993 },
                  html_instructions: 'Keep <b>right</b>, follow signs for <b>4S E</b> and merge onto <b>I-95 S</b>',
                  maneuver: 'keep-right',
                  polyline: { points: 'mqkxFduraMJ\\BL@J?B@J?LAFAFEJABCDCDEDGByAr@cChAGBGBEBE?A@C?A@A?A?EAA?CAACAEACCQ@SDWBSFQHWLUNWLQPUj@o@~@gA~@iA^c@^YJKLIXQXOXKf@MZE\\IJCNCj@Qj@QXK\\K|A]j@K`AOx@KF?h@G|@G@?@?XC`@Eh@EbBKD?lAGdAC|@Cr@AV?Z@`@@`@B`@Dl@H@??@^F^HZHtGzAtAZf@Jj@Hh@Fl@Dh@Bj@?j@Aj@Ah@En@G?A`@E`@Id@Kf@Od@Oh@Qd@Uj@WpB_AFEh@Sf@OXINEh@Mh@Ij@Ij@Eh@Cl@Av@A|HGrXU^Af@Ah@ENAFAj@G`@Ih@Kf@Mj@Q' },
                  start_location: { lat: 40.8605466, lng: -73.8288267 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.6 mi', value: 1044 },
                  duration: { text: '1 min', value: 46 },
                  end_location: { lat: 40.83042770000001, lng: -73.8328202 },
                  html_instructions: 'Keep <b>right</b> at the fork to stay on <b>I-95 S</b>, follow signs for <b>Triboro Bridge</b>/<b>Geo Washington Bridge</b>',
                  maneuver: 'fork-right',
                  polyline: { points: 'u~fxFb_raMtAWVERCRCVAT?T?T@RBTBTDTDRFRHTJRHPJRLPNPNPPPPLRPTHL?@DDJRLTJTVp@tCpH@BPd@Rb@LVP\\Tb@Zj@Zj@jCzEf@~@pAfChBhDNZN\\' },
                  start_location: { lat: 40.8370699, lng: -73.8252993 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '4.7 mi', value: 7524 },
                  duration: { text: '7 mins', value: 390 },
                  end_location: { lat: 40.8049873, lng: -73.91138750000002 },
                  html_instructions: 'Keep <b>left</b> at the fork to continue on <b>I-278 W</b>, follow signs for <b>Robert F. Kennedy Bridge</b>/<b>Manhattan</b>',
                  maneuver: 'fork-left',
                  polyline: { points: 'euexFbnsaMLJLXLVJVHTLXHVPf@HXHVHXHZHVFZHZFXDXF\\FXDZDZJXD\\DZFd@BP@N@@Df@Hx@BV@H?B@J@N?@@VDn@@TBd@@v@Bx@@x@FdG?x@?@@X?@@\\?B@v@Bz@@L?@@f@Dx@Dv@H`ADr@Dl@Db@@H?D?@Fb@Hx@Fj@?B@J@@?@Hr@LhADb@?FH~@XnBJp@@DlApJLrARrBFx@Hx@HlADh@T`DRjC`A~MJhBhCl_@Fn@d@rHHvALpBLlCPjEBn@DdA@f@Dl@^vFVlDFt@@R@J@P@PFp@l@`JPnCPxCThDFt@@XB^h@zGB\\JrAVxDVfDHtAHjADt@Dj@T|CF~@X|DBZt@nKDv@Fv@Dv@F|@Dr@Fz@J|AJhANzAHbBFtAJjAL~ABRDd@?@?B@F?HHZBHBHVj@lAnBvAdC@BLRP\\t@nALTPVTZPVRZRVPPNNh@n@XX`@d@f@f@d@d@VX`@`@d@b@VTTRTRzAxA`B`BDBhBjBn@f@l@n@xBzBlBrBxAxAvAzAfAhALLPPPTPPNRLPPTLPNTJPNTn@bAp@dAjGpJjGrJNXNVhFfI|DdGx@tANTFLJNFNFLHPHNHVHRJXFTfBvFTp@Rr@Rn@Rl@Tp@~DdL' },
                  start_location: { lat: 40.83042770000001, lng: -73.8328202 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.7 mi', value: 1113 },
                  duration: { text: '1 min', value: 73 },
                  end_location: { lat: 40.7980526, lng: -73.91970359999999 },
                  html_instructions: 'Keep <b>left</b> to stay on <b>I-278 W</b><div style="font-size:0.9em">Toll road</div>',
                  maneuver: 'keep-left',
                  polyline: { points: 'ev`xFdybbMlA~C^hARl@JXl@dBXv@\\`AFNBJDNBNDLBPBPDR@PBR@T@V@TB`A?P@NBN@LBLDLBLDJDHDJFHFFFFFHJFHBHDHBHBH@J?L@L?J@H@J@H@JBLBJDFDLD\\XrA|@p@b@dC~AzFtDfAp@fD|BPJ' },
                  start_location: { lat: 40.8049873, lng: -73.91138750000002 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.2 mi', value: 300 },
                  duration: { text: '1 min', value: 31 },
                  end_location: { lat: 40.7982231, lng: -73.9226152 },
                  html_instructions: 'Take exit <b>46</b> toward <b>Manhattan</b>/<b>FDR Drive</b><div style="font-size:0.9em">Toll road</div>',
                  maneuver: 'ramp-right',
                  polyline: { points: 'yj_xFbmdbMjAdADFBDDJBJDHBPBH@L@L@P?L?LAL?NANAJALALCJCLCNELGNELAD]bA[bAo@p@' },
                  start_location: { lat: 40.7980526, lng: -73.91970359999999 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.4 mi', value: 643 },
                  duration: { text: '1 min', value: 68 },
                  end_location: { lat: 40.8010139, lng: -73.9292926 },
                  html_instructions: 'Continue onto <b>New York State Reference Rte 900G</b>/<b>Robert F. Kennedy Bridge</b><div style="font-size:0.9em">Toll road</div>',
                  polyline: { points: '{k_xFj_ebM}@|BWl@M\\K^a@lA[rAQl@Ql@Sv@Sr@Qj@Qp@Sn@i@~AmEfNCJ' },
                  start_location: { lat: 40.7982231, lng: -73.9226152 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.4 mi', value: 715 },
                  duration: { text: '1 min', value: 49 },
                  end_location: { lat: 40.797215, lng: -73.9293301 },
                  html_instructions: 'Take the <b>F D R Dr S</b> exit on the <b>left</b><div style="font-size:0.9em">Toll road</div>',
                  maneuver: 'ramp-left',
                  polyline: { points: 'i}_xF`ifbMMd@k@fBIXGRGNCNCLCJAN?J?J?TBRFRBFBFFHHLJHDBJDPDP@J@REPIPMJKHMLYJW|@wCNWJQDGFKJIHIJILGJELELCNE~@En@ExCOr@CPAT?dAB' },
                  start_location: { lat: 40.8010139, lng: -73.9292926 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '8.8 mi', value: 14170 },
                  duration: { text: '14 mins', value: 821 },
                  end_location: { lat: 40.7015083, lng: -74.011977 },
                  html_instructions: 'Continue onto <b>FDR Drive</b>',
                  polyline: { points: 'se_xFhifbMT?H@N@P@P@NBPBNBRBNBPDNBNDPDPDNFPFNHNFNHNJLH\\TNJNJLLLLLLJNLNJNHPJRHRbCpF\\v@t@~ARb@Vh@Rb@Vf@T`@Tb@T`@Vb@Vb@X`@x@vAXb@X^V^Z^ZZVV\\ZZV\\V|@n@`Av@h@XNJNJNJNFNHPFNFNHPDNFjFfBPFNFNFNHRJRLPLPLPNRNNNjEpDNNRNNPNPNPNRLRLTFJHPJRJXhBrEfAlCJVLVJTLTLRNTNPNRNPNNPNPNRLPLRJPJTJRHTFRDRDTDTDR@P@N@P?P?PAPARANAPCPChBYPCNCPEPCNEPEPE`@KLERG^Ot@UtDwAPGNEPGNEPEPENENCpAWh@MVGpAO^ENAPANAL?L?N@L@NBPBNBLBNDNFLDNFNFJFNFLHNJNHNLPLPNNLpF|ERNRRJHLLJHJLJJJNLLPRJNLNx@jAZj@NVLRLRJPJNLNPTLNLLRR|@v@|AtAPPHHJJHJLLJJNN~@x@zAtARRPNLJf@b@f@\\NH~@n@LHJJLHRPzBlBVTHHJHLHNFJHJFXL`CrB`@^NLPNNNPNRPRRbBxA|ChCtAjAbBxARNJJPPPPPPLNTV~E~FHJ^h@xBtDHNR\\NRPRNPNPPLRPPLh@\\ZT\\RXRVPz@h@lBpANJLHNLNN|BpB`At@bAr@RLRNTNPLRPHLJJHLtApBPXNRPTTTRRTR`CrBtBbBRRVRZ^VVTVxDlDXTPPXTfVbRZT|AlA\\V^Z^\\Z\\^^hBlBZ\\\\Z^^d@^b@^d@Zd@ZRLf@ZZPZPzBnAb@XRJRJHBJDVJLFTHRHTHRFTFTFTFTDTDTDTBTDrDb@t@J`CVXDNBTDXHf@NRHTJPHNHPHPJNJrA|@pCfBb@ZVNLFTJRHTHRFRDXDT@RBT@N?F?T?RCRATETEVEr@MhDk@xB_@xB_@TE@?TEVEB?FA`@GrB]TGNC\\MVMBA@AZM\\WRQTUPSNQl@y@p@{@TY\\_@HIFEXSXSRKRITI`@KZGXEPATAX?T?f@Df@Bp@FzBPh@D`@F\\F^J\\Hf@Rf@Td@RVLb@TdAj@p@\\v@b@`Ah@xAv@`B|@d@VTLRJRHPHTHRHTFRFTDTDRBVBRB~@Fv@DxHb@h@DXBN@b@@n@Dn@Hh@Fh@Hj@Jh@Jh@Lh@Nf@Nf@P|@`@h@Tv@\\|@\\t@VfLxElBx@RHPHRJJFNLVPNLVT\\`@LPNTJPLTJTJTLZFPJZPj@FVLz@BPBR@L@R@TBX?TDlAFtBDnAFfADnB@ZDnADnAFhB?FB\\?J@D@RTfELtBP~CNfC\\dGDl@Dn@L|ALxAT`DNbBJlAXnDH`AFdAFhAL|AFpAN`BFn@Dp@Ft@Dl@HhADj@B\\Fh@BVDXDTFZHZHN@DDHDPJZJ\\FNDLXl@LZJVLRHPJTHRFLJTTf@f@nAXx@Tn@Rh@b@~@b@~@Vh@P\\P`@R^JTJVLVJRJRLT|CtF\\j@Zj@z@|Az@|A\\j@Zl@NVNVLTLTNXJRJRJRbBbDf@bAb@x@f@`AZd@FJDHDJDJDJFNDLDNBJDLBNBNBLBLBNBLBRBR~@`H' },
                  start_location: { lat: 40.797215, lng: -73.9293301 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.5 mi', value: 871 },
                  duration: { text: '1 min', value: 70 },
                  end_location: { lat: 40.7066222, lng: -74.01597749999999 },
                  html_instructions: 'Continue onto <b>Battery Park Underpass</b>',
                  polyline: { points: 'molwFzmvbMb@|CDXBT@V@L@N?H@N?N?RAP?PARARAVCPAVEVCPGTGTIVIRIRIROROTSVs@j@QL_@RC@A@QFA?UHa@L{FzAIBKBK@I@K@K@K?eA@G?K?I?IAIAMCKC{C}@KCMCMCk@OUISK' },
                  start_location: { lat: 40.7015083, lng: -74.011977 },
                  travel_mode: 'DRIVING' },
                { distance: { text: '0.5 mi', value: 725 },
                  duration: { text: '2 mins', value: 149 },
                  end_location: { lat: 40.7129366, lng: -74.0139476 },
                  html_instructions: 'Continue onto <b>NY-9A N</b>/<b>West St</b>',
                  polyline: { points: 'komwFzfwbMICKCs@UOEm@SOIw@UGCYKGCyBo@sA[QEsAa@oAY_@EcBOq@M_AWC?GEWKGAGCIAGA]E_AIu@IkAQkAUIA' },
                  start_location: { lat: 40.7066222, lng: -74.01597749999999 },
                  travel_mode: 'DRIVING' } ],
            traffic_speed_entry: [],
            via_waypoint: [] } ]
        ,
        overview_polyline: { points: 'qoqaGn~tpLcKKN`PdW\\dQe]p^yHpWvm@|ZrM_DbbAJjlCwRjgBmh@liAiC`jCnEf|Elj@zeE|Yp{Elj@viBvVvoFzGpsAp|@xzBfhAnkDyBf|BcRfwCvg@piDzi@hxAhO|iCvn@xlAvj@znAv_AjuFfkAb~E|eA`hAb}AzrBfw@pnCiB|tBl@zqHfZfdCtExjEd_@dyBrk@duAvUrtArTldDfSnfB|h@prAhcAntGfuAzzF|x@daCpb@~yBbRjcCvt@`_Dz}@jyEt{AbgBli@fk@vsAx\\|lCpcB|{Fv_El`BfzBdeDrpBlkDj}BrvArfAdtCxkI|rBhgBzSpd@jn@jgA`tCfbIv`BpnEdO|`BiK|~@jIxqDtbBpyCfs@voBbl@vrDfy@nvAjdAl}E|w@bz@f~AdcAvWfl@`C`y@j|@zcIac@h}BiJlxBvx@hiBfY`T|j@jWzAjfCrRbx@x\\Dba@x]zV|iArc@tl@lEn}Bne@z~AveC~lA~tDxjBHtxBlcAlf@xjDpzCly@r|AjnAf`AvtA|Nlr@uXvVaA`xAraAbq@vh@j`ArwBvq@lbAjLd~@nT`l@c]vnAiNtq@jXtoAzCzy@gDz|@sX~q@cf@fViIprBvV|_Cfm@|nAtr@hm@~r@xKjOr^va@j|B~c@vzB|nBveEjwAphG|x@x`Axs@`lA|k@xjAdUvZzc@zDry@{N~kA|jAtk@j~@iLvgBml@d~As^rfBbLlxAnGr|BjMdzAoH|r@nX`uApi@vqC{Z`fA~\\zpBd\\~xA~i@hu@h]bdA~n@AjUdCxMbj@si@bxEoMxu@pM~`Azg@tuEDr}@e^zgA_ThOhFnZ|k@@vn@~YjZ~~@hx@`bBjt@~`Ad~@`iAd`@rNbdA|JlYaApYfXroAvjAty@bPjfAvJ~iAla@ty@Ubt@wg@|w@g]rqAde@~xApi@txA_EjeBfQ|iAsPrxAbXxvAb`@peA~m@bkApM~rD~rAjvC`Dbw@fk@v\\~Q`m@sFbdBuZx`@tH~f@al@fRyJxx@|Tt{@~i@jr@`r@vh@rb@zNvg@nb@fl@hQvfAz\\xy@z{@zaCl`@lXrg@}AzdAbw@dRqKxLcQxQzG~YzYzw@lVrlA~OhbAxC|}ArO|f@zGdv@lr@_DnKrW_TvpAeEj~@}@z[ln@dIn}@f^x~EdOraAvj@fl@laAfwBt_@fUeB~VsOlo@jV_Kfp@vp@~q@vj@x_@yInUzM|}@hz@jcBd}AlaAza@~_AuN`yA~j@pPdyBli@foAwDjWo[Ied@wJ' },
        summary: 'I-84',
        warnings: [],
        waypoint_order: []
      }
    ],
    status: 'OK'
  },
  requestUrl: 'https://maps.googleapis.com/maps/api/directions/json?alternatives=true&destination=One%20World%20Trade%20Center&language=en&mode=driving&origin=02113&units=imperial&key=AIzaSyCgmYT7nWxLoPzwfsvsMuMRZ9i4cqCH9IA',
  query: {
    alternatives: true,
    destination: 'One World Trade Center',
    language: 'en',
    mode: 'driving',
    origin: '02113',
    units: 'imperial',
    key: 'AIzaSyCgmYT7nWxLoPzwfsvsMuMRZ9i4cqCH9IA'
  }
};